In [ ]:
%%capture
import os
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth
else:
    # Do this only in Colab notebooks! Otherwise use pip install unsloth
    !pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl triton cut_cross_entropy unsloth_zoo
    !pip install sentencepiece protobuf "datasets>=3.4.1" huggingface_hub hf_transfer
    !pip install --no-deps unsloth

In [ ]:
# This code block asks to restart session. Once restarted, the code blocks work fine
from datasets import load_dataset
from unsloth.chat_templates import standardize_sharegpt
from unsloth import FastLanguageModel
import torch
from datasets import load_dataset
from datasets import Dataset
from unsloth.chat_templates import get_chat_template
from unsloth.chat_templates import standardize_sharegpt
from transformers import TextStreamer
from trl import SFTConfig, SFTTrainer
from transformers import DataCollatorForSeq2Seq
from unsloth.chat_templates import train_on_responses_only
from sentence_transformers import SentenceTransformer
try:
  import chromadb
except:
  !pip install chromadb
  import chromadb
from chromadb.config import Settings
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import ast
import asyncio
!npx --yes playwright install
try:
  from crawl4ai import *
except:
  !pip install crawl4ai
  from crawl4ai import *
import regex as re
import pandas as pd
from pydantic import BaseModel
from typing import List
import requests
import json
import os
import csv
import time
import re
from datetime import datetime
import concurrent.futures
import tqdm
import random
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from dotenv import load_dotenv
import ast
import nest_asyncio
import asyncio
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, concat, lit, length
from pyspark.sql.types import ArrayType, StringType, StructType, StructField
from pyspark.sql import functions as F
from pyspark.sql.window import Window
try:
  import findspark
except:
  !pip install findspark
  import findspark
try:
  import evaluate
except:
  !pip install evaluate
  import evaluate
!pip install rouge_score

from xml.etree import ElementTree as ET
import csv
import xml
try:
  from ragas import SingleTurnSample
  from ragas.metrics import ResponseRelevancy
except:
  !pip install ragas

from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
import numpy as np
try:
  from ragas.metrics import answer_relevancy
  from ragas.metrics import Faithfulness
  from ragas.metrics import ResponseRelevancy
except:
  !pip install ragas
  from ragas.metrics import answer_relevancy
  from ragas.metrics import Faithfulness
  from ragas.metrics import ResponseRelevancy

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋╔═══════════════════════════════════════════════════════════════════════════════╗
║ WARNING: It looks like you are running 'npx playwright install' without first ║
║ installing your project's dependencies.                                       ║
║                                                                               ║
║ To avoid unexpected behavior, please install your dependencies first, and     ║
║ then run Playwright's install command:                                        ║
║                                                                               ║
║     npm install                                                               ║
║     npx playwright install                                                    ║
║                                                                               ║
║ If your project does

**Section 0 : Supervised Fine-Tuning model**

##############Beauty q-n-a dataset################
##############for fine-tuning Qwen model##########

In [ ]:
from google.colab import files

In [ ]:
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/PrepData_for_SFT.ipynb' /content/sample_data
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/FineTune_model.ipynb' /content/sample_data
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/standardize_custom_format.ipynb' /content/sample_data
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/formatting_prompts_func.ipynb' /content/sample_data

In [ ]:
%run /content/sample_data/PrepData_for_SFT.ipynb
%run /content/sample_data/FineTune_model.ipynb
%run /content/sample_data/standardize_custom_format.ipynb
%run /content/sample_data/formatting_prompts_func.ipynb

In [ ]:
# Unsloth used as it facilitates fine-tuning and training of LLMs faster. [class]It took the model and quantized it into bits.
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
# Sets the context window during fine-tuning or inference: It establishes how many tokens the model will accept from your input before it hits the cutoff and either truncates or wraps.
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
  model_name = "Qwen/Qwen2.5-1.5B-Instruct", # or choose "unsloth/Llama-3.2-1B-Instruct"
  max_seq_length = max_seq_length,
  dtype = dtype,
  load_in_4bit = load_in_4bit,
  # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

beauty_qa_standardizedV2 = PrepData_for_SFT(tokenizer)
# The intermediate outputs printed below are: how customer reviews data looks like after uploading. And after merging metadata to the main dataset
# The final outputs printed below are how the data looks like, after applying system, user, assistant format to it.

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
model = FineTune_model(beauty_qa_standardizedV2, model, tokenizer, max_seq_length)

Unsloth 2025.8.1 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.


Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/500 [00:00<?, ? examples/s]

Map (num_proc=2):   0%|          | 0/500 [00:00<?, ? examples/s]

Before fine-tuning:

GPU = Tesla T4. Max memory = 14.741 GB.
1.525 GB of memory reserved.


==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 500 | Num Epochs = 1 | Total steps = 10
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)


28.5808 seconds used for training.
0.48 minutes used for training.
Peak reserved memory = 2.248 GB.
Peak reserved memory for training = 0.723 GB.
Peak reserved memory % of max memory = 15.25 %.
Peak reserved memory for training % of max memory = 4.905 %.


In [ ]:
# Take your fine-tuned model, have it answer few questions from test dataset
# I picked last 5 questions in the qa_Beauty.csv
prompts = ["Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. how can i use it for Deep Conditioning Session?",\
           # Answer in dataset:
           # You can use it as a pre-shampoo treatment, where you apply the oil to hair and scalp. your hair can be dry or you can slightly make your hair damp. Then put a conditioning cap on, sit under a dryer, a hot oil deep treatment. Another option: after you have washed your hair, apply oil to your hair. You can either sit under a dryer 20 mins or after you have applied the oil, you can put your favorite deep conditioner on top of of the oil as well and then sit under the drier for a deep treatment.20-30 mins
           "Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. how can i use it for In-Shower Application?",\
           # Answer in dataset:
           # Application during shower takes less time. After shampooing hair, simply massage some oil through your hair just like you would use a regular conditioner. Thick, curly, or coarse hair can benefit from applying argan oil to the whole head, while those with fine for thin hair should probably only apply from the middle of the length to the ends. Leave the oil in for a few minutes to absorb, and then rinse it out.
           "Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. how can i use it for Topical Use on Dry Hair?",\
           # Answer in dataset:
           # A little goes a long way! A drop or two, depending on the length and condition of your hair, will suffice. Smooth down the hair shaft for taming frizz, split ends, and flyaways, while conditioning and adding shine
           "Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. is it good for nail beauty?",\
           # Answer in dataset: I would say it's good for cuticles. I can't say about the nail itself. Probably will give them a nice shine.
           "Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. I find myself with rough cuticles right around the nail, should I use Argan Oil and how?"\
           # Answer in dataset: Yes, you can. In the evening before you go to bed, wash your hands very well and add the argan oil to your cuticles and put on some gloves. If they are really rough you may have to repeat the process!
           ]
# prompt = "Cut Glass Powder Box. What size powder puff is recommended? Would a 4.5 inches diameter puff be too large for the box? Thanks, Joanne"
predictions = []
for prompt in prompts:
  print(f"User question is: {prompt}")
  messages = [
      {"role": "system", "content": "You are a helpful AI assistant specialized in beauty and cosmetics. User will mention beauty product name and then ask a related question. Provide a clear and accurate answer."},
      {"role": "user", "content": prompt}
  ]

  input_ids = tokenizer.apply_chat_template(
      messages,
      tokenize = True,
      add_generation_prompt = True, # Must add for generation
      return_tensors = "pt",
  ).to("cuda")

  text_streamer = TextStreamer(tokenizer, skip_prompt = True)
  print("Generating output:..\n")
  output = model.generate(input_ids, streamer = text_streamer, max_new_tokens = 128, pad_token_id = tokenizer.eos_token_id, use_cache = True, temperature = 0.1, min_p = 0.1)
  # TextStreamer streams the tokens to stdout (i.e., prints them as they’re generated) but doesn’t return the generated text.
  # print(f"{tokenizer.batch_decode(output)}")
  print()
  decoded_output = tokenizer.decode(output[0], skip_special_tokens=True).split("assistant\n")[-1].strip()
  predictions.append(decoded_output)

  # The chatbot does understand qna well. Most answers make sense. Some places, it hallucinates a bit.
  # The answers generated by the fine-tuned model are too short. The answers in the dataset are more detailed.
  # Example-
  # User question is: Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. how can i use it for Deep Conditioning Session?
  # Answer in dataset: You can use it as a pre-shampoo treatment, where you apply the oil to hair and scalp. Your hair can be dry or you can slightly make your hair damp. Then put a conditioning cap on, sit under a dryer, a hot oil deep treatment. Another option: after you have washed your hair, apply oil to your hair. You can either sit under a dryer 20 mins or after you have applied the oil, you can put your favorite deep conditioner on top of the oil as well and then sit under the drier for a deep treatment. 20-30 mins.
  # Answer given by chatbot: Apply the oil to your scalp and massage into your hair. Leave on overnight or at least 2 hours. Use this method once a week.

User question is: Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. how can i use it for Deep Conditioning Session?
Generating output:..

Apply the oil to your scalp and massage into your hair. Leave on overnight or at least 2 hours. Use this method once a week.<|im_end|>

User question is: Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. how can i use it for In-Shower Application?
Generating output:..

Apply the oil to your scalp before shampooing or after washing your hair. Use as much as you need.<|im_end|>

User question is: Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. how can i use it for Topical Use on Dry Hair?
Generating output:..

Apply the oil to your scalp and massage into your hair. Leave on overnight or at least 2 hours before washing.<|im_end|>

User question is: Moroccan Argan Oil - For Hair, Face, Skin, &amp; Nails, By Natural Beauty Brand. is it good for nail beauty?
Gene

In [ ]:
references = [
    "You can use it as a pre-shampoo treatment, where you apply the oil to hair and scalp. Your hair can be dry or you can slightly make your hair damp. Then put a conditioning cap on, sit under a dryer, a hot oil deep treatment. Another option: after you have washed your hair, apply oil to your hair. You can either sit under a dryer 20 mins or after you have applied the oil, you can put your favorite deep conditioner on top of the oil as well and then sit under the drier for a deep treatment. 20-30 mins.",
    "After shampooing hair, massage some oil through your hair just like you would use a conditioner. Thick, curly, or coarse hair can benefit from applying argan oil to the whole head. For fine or thin hair, apply from mid-length to ends. Leave it for a few minutes, then rinse.",
    "A drop or two, depending on hair length and condition, will suffice. Smooth down the shaft to tame frizz, split ends, and flyaways while adding shine.",
    "I would say it's good for cuticles. I can't say about the nail itself. Probably will give them a nice shine.",
    "Yes, you can. In the evening before bed, wash your hands, apply argan oil to your cuticles, and wear gloves. Repeat if needed for very rough cuticles."
]
rouge = evaluate.load("rouge")
rouge_result = rouge.compute(predictions=predictions, references=references)
print("ROUGE-L:", rouge_result["rougeL"])

ROUGE-L: 0.11541482750566837


First, I calculate ROUGE score for test prompts in my data used for fine-tuning. This is qna data from Amazon Reviews. This has ***NO*** questions about safety of ingredients.    
ROUGE score measures the overlap between a generated text (like a summary or translation) and a reference text (a human-written summary or translation). Higher ROUGE scores indicate greater similarity and better quality of the generated text.    
    
On average, only ~11% of the reference tokens are part of the longest subsequence shared with the model’s output.   
The low ROUGE score could be because of:     
The answers generated by the fine-tuned model are too short. The answers in the dataset are more detailed.   
Example-   
User question is: Moroccan Argan Oil - For Hair, Face, Skin, amp; Nails, By Natural Beauty Brand. how can i use it for Deep Conditioning Session?   
Answer in dataset: You can use it as a pre-shampoo treatment, where you apply the oil to hair and scalp. Your hair can be dry or you can slightly make your hair damp. Then put a conditioning cap on, sit under a dryer, a hot oil deep treatment. Another option: after you have washed your hair, apply oil to your hair. You can either sit under a dryer 20 mins or after you have applied the oil, you can put your favorite deep conditioner on top of the oil as well and then sit under the drier for a deep treatment. 20-30 mins.   
Answer given by chatbot: Apply the oil to your scalp and massage into your hair. Leave on overnight or at least 2 hours. Use this method once a week.   

  
However, in general, the chatbot does understand qna well. Most answers make logical and semantic sense. So this does behave like a chatbot right now. With supervised fine-tuning, it will get more context for answering questions and the answers will become more accurate and precise.

Next, I calculate answer relevancy score for questions asking ***about ingredients used in the beauty products.***   
Source for understanding relevance score- https://docs.ragas.io/en/v0.1.21/concepts/metrics/answer_relevance.html.  
The evaluation metric, Answer Relevancy, focuses on assessing how pertinent the generated answer is to the given prompt. A lower score is assigned to answers that are incomplete or contain redundant information and higher scores indicate better relevancy.    
AnswerRelevance.score_batch() takes two parallel lists: the input questions (prompts) and the corresponding model-generated responses, and returns a relevance score between 0 and 1 for each pair   
I am using this metric as I do not have ground truth answers for questions asking about safety of ingredients. I am unable to calculate the ROUGE score for this reason. There is no such dataset available. Answer Relevance can be calulated without ground truth answers or context.  
  
There is this difficulty in calculating a base matric. But this is what makes this project exciting to me. Lack of such a curated dataset suggests that no such work on a large scale exists today.

In [ ]:
from google.colab import userdata
api_key = userdata.get('OPENAI_API_KEY')
os.environ["OPENAI_API_KEY"] = api_key

In [ ]:
from ragas.metrics import answer_relevancy
from ragas import evaluate

# Checking Answer Relevancy for questions asking about safety of ingredients used in beauty products
test_prompts = ["Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?", \
                "Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?", \
                "Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?", \
                "Is zirconium-containing complexes in cosmetics safe?", \
                "Is Triclosan in over-the-counter cosmetics safe for me and the environment?",\
                "Can Benzophenone in my makeup product be a hormone disruptor?",\
                "Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys",\
                "Can fragnances cause dermatitis and allergic reactions?",\
                "Is there any evidence of phenylenediamine in hair dye causing cancer?",\
                "Can parabens found in cosmetics cause any damage to the human body?",\
                "Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk",\
                "Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?",\
                "Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?",\
                "Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body",\
                "Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?",\
                "Do talc‑based powders risk contamination with asbestos?"]
relevance_scores = []
for prompt in test_prompts:
  print(f"User question is: {prompt}")

  augmented_prompt = [
        {"role": "system", "content": "You are a helpful AI assistant specialized in answering questions about harmful side-effects of ingredients in cosmetics. " },
        {"role": "user", "content": prompt}
    ]

  input_ids = tokenizer.apply_chat_template(
      augmented_prompt,
      tokenize = True,
      add_generation_prompt = True, # Must add for generation
      return_tensors = "pt",
  ).to("cuda")

  text_streamer = TextStreamer(tokenizer, skip_prompt = True)
  print("Generating output:..\n")
  output = model.generate(input_ids, streamer = text_streamer, max_new_tokens = 128, pad_token_id = tokenizer.eos_token_id, use_cache = True, temperature = 0.1, min_p = 0.1)
  # TextStreamer streams the tokens to stdout (i.e., prints them as they’re generated) but doesn’t return the generated text.
  # print(f"{tokenizer.batch_decode(output)}")
  print()
  decoded_output = tokenizer.decode(output[0], skip_special_tokens=True).split("assistant\n")[-1].strip()


  data_samples = {
    'question': [prompt],
    'answer': [decoded_output]
  }
  dataset_Vf = Dataset.from_dict(data_samples)
  score = evaluate(dataset_Vf,metrics=[answer_relevancy])
  relevance_scores.append(score)

print(relevance_scores)
print(f"Average relevance score: {np.mean(relevance_scores):.3f}")
print(f"Scores per example: {relevance_scores}")

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


User question is: Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?
Generating output:..

I'm not sure if you're asking about the chemical or the product name, but I'll assume it's the latter. The word "ultra" is often used to indicate that something is very strong or powerful. So, Ultra Slay might be referring to an extremely powerful or effective lipstick. However, there isn't any evidence that this particular ingredient would cause skin irritation. It's always best to do your own research and consult with a dermatologist before using any new cosmetic products.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?
Generating output:..

Butylated Hydroxytoluene (BHT) is an antioxidant that's used as a preservative to prevent rancidity and other changes in color, odor, or flavor. It can be found in many products including lipsticks, deodorants, lotions, shampoos, conditioners, and hair dyes. BHT has been shown to cause liver damage in animals. There have also been reports of skin irritation from using it on the lips.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?
Generating output:..

Phenyl ethane-2,3-diol (also known as Phenoxyethanol) is not considered to be an endocrine disruptor. It is used as a preservative and stabilizer for lipsticks.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is zirconium-containing complexes in cosmetics safe?
Generating output:..

Zirconium is not known to cause any adverse effects when used as a cosmetic ingredient.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is Triclosan in over-the-counter cosmetics safe for me and the environment?
Generating output:..

Triclosan is an antibacterial agent that has been used as an ingredient in many products, including toothpaste, soaps, shampoos, deodorants, and hand sanitizers. It's also found in some sunscreens. Triclosan is not approved by the FDA to be used on skin or in food contact surfaces. The use of triclosan in consumer products has increased dramatically since the 1970s when it was first introduced into the market. Triclosan is considered safe for humans because it does not accumulate in the body. However, there have been concerns raised regarding its safety



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can Benzophenone in my makeup product be a hormone disruptor?
Generating output:..

Benzophenone is not considered to be an endocrine disruptor, but it can cause skin irritation and allergic reactions.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys
Generating output:..

Parabens and Phenols are not the same thing, but they both have been shown to be endocrine disruptors. Endocrine disruptors are chemicals that interfere with the body's hormone system. Parabens are used as preservatives in many cosmetic products including shampoos, lotions, soaps, and deodorants. Phenols are organic compounds that can also act as preservatives. Both have been linked to early puberty in children.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can fragnances cause dermatitis and allergic reactions?
Generating output:..

Yes, fragrances can cause skin irritation or allergies. Fragrance is the most common ingredient that causes these problems.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is there any evidence of phenylenediamine in hair dye causing cancer?
Generating output:..

Yes, the use of phenylenediamine (PDA) has been linked to an increased risk of developing non-Hodgkin's lymphoma.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can parabens found in cosmetics cause any damage to the human body?
Generating output:..

Parabens are used as preservatives in many cosmetic products, including shampoos and lotions. Parabens have been shown to be absorbed through the skin into the bloodstream. The concern is that these chemicals may disrupt hormone function or interfere with normal cell growth.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk
Generating output:..

Yes, it can. Formaldehyde is used as a preservative and to keep the product from breaking down. It's also an irritant that causes allergic reactions. The amount of formaldehyde in these products is not regulated by the FDA.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?
Generating output:..

Yes, it can. The use of mercury-containing products has been linked to kidney damage and other health problems.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?
Generating output:..

Yes, they can be. Phthalates have been shown to cause testicular damage in rats.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body
Generating output:..

I'm not aware of any studies that have looked at this, but I would be very surprised if they did not accumulate in the body.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?
Generating output:..

Yes, there is evidence that some lipsticks contain lead, which can cause developmental problems if ingested. Lead is also found in nail polish removers, but it's not as common in lipstick.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Do talc‑based powders risk contamination with asbestos?
Generating output:..

Yes, talcum powder is often contaminated with asbestos.<|im_end|>



Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

[{'answer_relevancy': 0.0000}, {'answer_relevancy': 0.8687}, {'answer_relevancy': 0.8903}, {'answer_relevancy': 0.9412}, {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.9473}, {'answer_relevancy': 0.8481}, {'answer_relevancy': 0.9417}, {'answer_relevancy': 0.8781}, {'answer_relevancy': 0.9020}, {'answer_relevancy': 0.8472}, {'answer_relevancy': 0.8807}, {'answer_relevancy': 0.8862}, {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.8872}, {'answer_relevancy': 0.9670}]


TypeError: unsupported operand type(s) for +: 'EvaluationResult' and 'EvaluationResult'

**RAG dataset**.  
**Section 1: When query is for searching scientific articles in PubMed**

Code to fetch data from PubMed is saved in below ipython notebook.
PubMed can block requests if usage limit is exceeded.   
Hence, ran below code once, downloaded the csv on my local system and uploading it for every session of colab

In [ ]:
# GetPubMed_data.ipynb

README.md: 0.00B [00:00, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/7.67M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/11550 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2888 [00:00<?, ? examples/s]

In [ ]:
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/PrepData_for_RAG.ipynb' /content/sample_data
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/factual_answers.ipynb' /content/sample_data

In [ ]:
%run /content/sample_data/PrepData_for_RAG.ipynb
%run /content/sample_data/factual_answers.ipynb

In [ ]:
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

In [ ]:
# Test with a sample query
collection = PrepData_for_RAG()
test_query = "Is polyethylene in my lipstick safe? Does it have any side effects?\n"
test_query_emb = embedding_model.encode(test_query)

results = collection.query(
    query_embeddings=test_query_emb,
    n_results=5
)
print(results)

Output hidden; open in https://colab.research.google.com to view.

The answers produced below are qualitatively making sense. And are accurate basis the texts provided as context to the RAG model.  
Since, I do not have any correct answer available for these questions due to lack of a dataset containing ground truth for the beauty/cosmetics industry, I am implementing the metrics - answer relevancy, response relevancy and response faithfulness from the CleanLab company.
Source: https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/answer_relevance/#response-relevancy,    
https://cleanlab.ai/blog/rag-tlm-hallucination-benchmarking/    
I am unable to calculate the ROUGE score and compare against a benchmark ROUGE score.

In [ ]:
from ragas.metrics import answer_relevancy
from ragas import evaluate

# Checking Answer Relevancy for questions asking about safety of ingredients used in beauty products
test_prompts = ["Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?", \
                "Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?", \
                "Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?", \
                "Is zirconium-containing complexes in cosmetics safe?", \
                "Is Triclosan in over-the-counter cosmetics safe for me and the environment?",\
                "Can Benzophenone in my makeup product be a hormone disruptor?",\
                "Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys?",\
                "Can fragnances cause dermatitis and allergic reactions?",\
                "Is there any evidence of phenylenediamine in hair dye causing cancer?",\
                "Can parabens found in cosmetics cause any damage to the human body?",\
                "Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk",\
                "Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?",\
                "Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?",\
                "Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body?",\
                "Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?",\
                "Do talc‑based powders risk contamination with asbestos?"]
relevance_scores = []
for prompt in test_prompts:
  print(f"User question is: {prompt}")

  print()
  response, context = factual_answers(prompt, collection)

  data_samples = {
    'question': [prompt],
    'answer': [response]
  }
  dataset_Vf = Dataset.from_dict(data_samples)
  score = evaluate(dataset_Vf,metrics=[answer_relevancy])
  relevance_scores.append(score)

print(relevance_scores)
# print(f"Average relevance score: {np.mean(relevance_scores):.3f}")
print(f"Scores per example: {relevance_scores}")

User question is: Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?

Generating output:..
No, it would not. It's a moisturizing agent.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, butylated hydroxytoluene is generally considered safe for use in lipstick. It's also known as BHT, and it acts as a preservative.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, it is not.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is zirconium-containing complexes in cosmetics safe?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 30 zirconium-containing complexes as used in cosmetic formulations; these complexes are specifically of the following types: ZrO2, ZrCl4, ZrF4, ZrCO3, Zr(OH)4, ZrSbF6, ZrSbF8, ZrSbF10, ZrSbF12, ZrSbF14, ZrSbF16, ZrSbF18, ZrSbF20, Zr


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is Triclosan in over-the-counter cosmetics safe for me and the environment?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The abstract states that "the Panel reviewed available animal and clinical data related to these ingredients" and concluded that TCS is safe in cosmetic formulations.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Unsloth: Input IDs of length 3023 > the model's max sequence length of 2048.
We shall truncate it ourselves. It's imperative if you correct this issue first.


User question is: Can Benzophenone in my makeup product be a hormone disruptor?

Generating output:..
 irregularities in the shape of the breast, including asymmetry, distortion, and abnormal size, which can lead to psychological distress and affect self-esteem. Breast cancer is one of the leading causes of death among women worldwide. It has been suggested that benzophenone-3 (BP-3), a common UV filter found in sunscreens and cosmetics, could potentially cause breast cancer through mechanisms such as altering estrogen receptor gene expression in the uterus and stimulating the proliferation of the mammary gland. To assess the potential carcinogenic effects of benzophenone-3, researchers conducted a study involving male and female rats and mice. They fed them


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The abstract states "Parabens are the most frequently used preservative in dermatological medications."<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can fragnances cause dermatitis and allergic reactions?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, fragrances can cause dermatitis and allergic reactions.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Is there any evidence of phenylenediamine in hair dye causing cancer?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, there is no evidence that phenylenediamine causes cancer.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can parabens found in cosmetics cause any damage to the human body?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, some people may experience allergic reactions or other health problems when they come into contact with certain types of parabens. These can include rashes, itching, redness, swelling, and even more serious conditions like anaphylaxis.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The following is my answer based on the provided context:

Yes, formaldehyde has been linked to increased cancer risks. Formaldehyde is a known carcinogen and exposure to it through nail hardeners or hair-smoothing keratin treatments can lead to increased cancer risks. It's important to choose products that do not contain formaldehyde or other harmful chemicals.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, it can.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, they are not.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The expert panel does not consider long-chain PFAS to be problematic in cosmetics.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

User question is: Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?

Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The expert panel concluded that there is no evidence of developmental or carcinogenic risk associated with the use of color cosmetics containing lead, cadmium, chromium, nickel, or mercury.<|im_end|>


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Unsloth: Input IDs of length 2227 > the model's max sequence length of 2048.
We shall truncate it ourselves. It's imperative if you correct this issue first.


User question is: Do talc‑based powders risk contamination with asbestos?

Generating output:..
ialltracervallyinstilledratswereevaluatedbyhistopathologyimmediatelyafterexposure,astwellasafter2weeksand3,6,12monthspostexposure.Inthesefirststudygroupsofrattworeexposedtohighexposure(dose)concentrationsoftitaniumoxideparticleformulationsfor4weeksataerosolconcentrationrangefrom1130-1300mg/m(3)lungtissuesweresampledbyhistopathologyimmediatelyafterexposure,asanewasassessedat2weeksand3,6,12month


Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

[{'answer_relevancy': 0.8003}, {'answer_relevancy': 0.9657}, {'answer_relevancy': 0.7471}, {'answer_relevancy': 0.9310}, {'answer_relevancy': 0.8457}, {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.8385}, {'answer_relevancy': 0.9439}, {'answer_relevancy': 0.9412}, {'answer_relevancy': 0.9202}, {'answer_relevancy': 0.9057}, {'answer_relevancy': 0.7462}, {'answer_relevancy': 0.7478}, {'answer_relevancy': 0.8917}, {'answer_relevancy': 0.9062}, {'answer_relevancy': 0.7973}]
Scores per example: [{'answer_relevancy': 0.8003}, {'answer_relevancy': 0.9657}, {'answer_relevancy': 0.7471}, {'answer_relevancy': 0.9310}, {'answer_relevancy': 0.8457}, {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.8385}, {'answer_relevancy': 0.9439}, {'answer_relevancy': 0.9412}, {'answer_relevancy': 0.9202}, {'answer_relevancy': 0.9057}, {'answer_relevancy': 0.7462}, {'answer_relevancy': 0.7478}, {'answer_relevancy': 0.8917}, {'answer_relevancy': 0.9062}, {'answer_relevancy': 0.7973}]


***Comparison of fine-tuned model vs. RAG***.
Here, I am using the same set of test prompts to fine-tuned model and RAG model.   
Copying response and answer relevancy scores from fine-tuned model calculated earlier -     
Prompt 1: Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?    
fine-rune model response: I'm not sure what you mean by "polethylene" - it's not an ingredient that I know of, but if you're talking about polyethylene glycol (PEG), then yes, it can cause skin irritation. It is used as a humectant and emollient to help keep your lips moisturized.    
fine-tune model answer relevancy score: 0.0.
  
RAG model response: No, it would not. It's a moisturizing agent.     
RAG model answer relevancy score: 0.8003.  

**********************

Prompt 2: Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?    
fine-tuned model response: Butylated Hydroxytoluene (BHT) is an antioxidant that's used as a preservative to prevent the growth of bacteria and fungi in products like lipsticks, lotions, and other personal care items. It's considered safe when used at low concentrations. However, it can cause skin irritation or allergic reactions in some people.        
fine-rune model answer relevancy score: 0.886.   
  
RAG model response: No, butylated hydroxytoluene is generally considered safe for use in lipstick. It's also known as BHT, and it acts as a preservative.    
RAG model answer relevancy score: 0.9657.  
**********************

Prompt 3: Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?        
fine-tuned model response: Phenyl ethane-2,3-diol is used as a preservative and stabilizer for lipsticks. It has been shown to be an endocrine disruptor.       
fine-rune model answer relevancy score: 0.88.   
    
RAG model response: No, it is not.     
RAG model answer relevancy score: 0.7471.  
**********************  
   
Prompt 4: Is zirconium-containing complexes in cosmetics safe?       
fine-tuned model response: Zirconium is not known to cause any harm when used as an ingredient in cosmetic products. Zirconium compounds have been used for many years in the manufacture of ceramics, glass and other materials.         
fine-rune model answer relevancy score: 0.964.
  
RAG model response: The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 30 zirconium-containing complexes as used in cosmetic formulations; these complexes are specifically of the following types: ZrO2, ZrCl4, ZrF4, ZrCO3, Zr(OH)4, ZrSbF6, ZrSbF8, ZrSbF10, ZrSbF12, ZrSbF14, ZrSbF16, ZrSbF18, ZrSbF20, Zr   
RAG model answer relevancy score: 0.9310.
**********************  
   
Prompt 5: Is Triclosan in over-the-counter cosmetics safe for me and the environment?        
fine-tuned model response: Triclosan is an antibacterial agent that has been used as a preservative in many products, including toothpaste, deodorants, soaps, shampoos, and hand sanitizers. It's also found in some personal care products like nail polish removers, hair color, and skin moisturizers. Triclosan is considered to be one of the most widely used antimicrobial agents in consumer products. The Environmental Protection Agency (EPA) regulates triclosan because it can enter waterways through wastewater treatment plants and may have adverse effects on aquatic life. In fact, the EPA banned its use in household cleaning.   
fine-tune model answer relevancy score: 0.8900.   
  
RAG model response: The abstract states that "the Panel reviewed available animal and clinical data related to these ingredients" and concluded that TCS is safe in cosmetic formulations.    
RAG model answer relevancy score: 0.8457.

**********************  
   
Prompt 6: Can Benzophenone in my makeup product be a hormone disruptor?          
fine-tuned model response: Benzophenone is an ingredient that can cause skin irritation and allergic reactions, but it does not appear to have any hormonal effects.   
fine-tune model answer relevancy score: 0.898.   
  
RAG model response: irregularities in the shape of the breast, including asymmetry, distortion, and abnormal size, which can lead to psychological distress and affect self-esteem. Breast cancer is one of the leading causes of death among women worldwide. It has been suggested that benzophenone-3 (BP-3), a common UV filter found in sunscreens and cosmetics, could potentially cause breast cancer through mechanisms such as altering estrogen receptor gene expression in the uterus and stimulating the proliferation of the mammary gland. To assess the potential carcinogenic effects of benzophenone-3, researchers conducted a study involving male and female rats and mice. They fed them    
RAG model answer relevancy score: 0.0000.
**********************  
   
Prompt 7: Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys?   
fine-tuned model response: Parabens are preservatives that have been shown to be absorbed through the skin, but there is no evidence that they cause early puberty. Phenols can also be absorbed through the skin, but there is no evidence that they cause early puberty either.     
fine-tune model answer relevancy score: 0.0.
RAG model response: irregularities in the shape of the breast, including asymmetry, distortion, and abnormal size, which can lead to psychological distress and affect self-esteem. Breast cancer is one of the leading causes of death among women worldwide. It has been suggested that benzophenone-3 (BP-3), a common UV filter found in sunscreens and cosmetics, could potentially cause breast cancer through mechanisms such as altering estrogen receptor gene expression in the uterus and stimulating the proliferation of the mammary gland. To assess the potential carcinogenic effects of benzophenone-3, researchers conducted a study involving male and female rats and mice. They fed them    
RAG model answer relevancy score: 0.8385.
**********************  
   
Prompt 8: Can fragnances cause dermatitis and allergic reactions?   
fine-tuned model response: Yes, fragrances can cause skin irritation or other adverse effects. The fragrance chemicals may be irritating to the skin, causing redness, itching, burning, or swelling. Some people have an allergy to certain fragrance chemicals that causes more severe reactions such as hives, difficulty breathing, or even anaphylaxis.    
fine-tune model answer relevancy score: 0.927
RAG model response: Yes, fragrances can cause dermatitis and allergic reactions.      
RAG model answer relevancy score: 0.9439.   
**********************  
   
Prompt 9: Is there any evidence of phenylenediamine in hair dye causing cancer?   
fine-tuned model response: Yes, the use of phenylenediamine (PDA) has been linked to an increased risk of developing non-Hodgkin's lymphoma.    
fine-tune model answer relevancy score: 0.878.  
RAG model response: No, there is no evidence that phenylenediamine causes cancer.          
RAG model answer relevancy score: 0.9412.  
**********************  
   
Prompt 10: Can parabens found in cosmetics cause any damage to the human body?   
fine-tuned model response: Parabens are used as preservatives in many cosmetic products, including shampoos and lotions. Parabens have been shown to be absorbed through the skin and enter the bloodstream. They can also accumulate in breast milk and urine. The long-term effects on humans is not known.    
fine-tune model answer relevancy score: 0.0000.  
RAG model response: Yes, some people may experience allergic reactions or other health problems when they come into contact with certain types of parabens. These can include rashes, itching, redness, swelling, and even more serious conditions like anaphylaxis.            
RAG model answer relevancy score: 0.9202.  
**********************  
   
Prompt 11: Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk?   
fine-tuned model response: Yes, it can. Formaldehyde is used as a preservative and to keep the product from breaking down. It's also an irritant that causes skin rashes and allergic reactions. The International Agency for Research on Cancer (IARC) has classified formaldehyde as a human carcinogen.   
fine-tune model answer relevancy score: 0.8357.  
RAG model response: Yes, formaldehyde has been linked to increased cancer risks. Formaldehyde is a known carcinogen and exposure to it through nail hardeners or hair-smoothing keratin treatments can lead to increased cancer risks. It's important to choose products that do not contain formaldehyde or other harmful chemicals.    
RAG model answer relevancy score: 0.9057.    
**********************  
   
Prompt 12: Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?   
fine-tuned model response: Yes, it can. The kidneys filter out toxins from the body and if they become overloaded with mercury, they may not be able to function properly. This is especially true if you have other health conditions that put your kidneys at risk such as diabetes or high blood pressure.   
fine-tune model answer relevancy score: 0.8870  
RAG model response: Yes, it can.     
RAG model answer relevancy score: 0.7462.    
**********************  
   
Prompt 13: Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?     
fine-tuned model response: Yes, both have been shown to cause harm to the male reproductive system.  
fine-tune model answer relevancy score: 0.8558  
RAG model response: No, they are not.     
RAG model answer relevancy score: 0.7478.       
**********************  
   
Prompt 14: Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body?        
fine-tuned model response: Yes, they do. The long chain PFAS can be absorbed through the skin and accumulate in the body over time.      
fine-tune model answer relevancy score: 0.9210.  
RAG model response: The expert panel does not consider long-chain PFAS to be problematic in cosmetics.     
RAG model answer relevancy score: 0.8917.   
**********************  
   
Prompt 15: Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?           
fine-tuned model response: Yes, it is possible for color cosmetics to contain heavy metals such as lead, cadmium, chromium, nickel, and mercury. These can cause skin irritation, allergic reactions, and even cancer if ingested or absorbed through the skin. The risk increases when the products are applied to sensitive areas like the lips or eyelids.        
fine-tune model answer relevancy score: 0.9460  
RAG model response: The expert panel concluded that there is no evidence of developmental or carcinogenic risk associated with the use of color cosmetics containing lead, cadmium, chromium, nickel, or mercury.   
RAG model answer relevancy score: 0.9062.    
**********************  
   
Prompt 16: Do talc‑based powders risk contamination with asbestos?             
fine-tuned model response: Yes, talcum powder is often contaminated with asbestos.       
fine-tune model answer relevancy score: 0.9668  
RAG model response: ialltracervallyinstilledratswereevaluatedbyhistopathologyimmediatelyafterexposure,astwellasafter2weeksand3,6,12monthspostexposure.Inthesefirststudygroupsofrattworeexposedtohighexposure(dose)concentrationsoftitaniumoxideparticleformulationsfor4weeksataerosolconcentrationrangefrom1130-1300mg/m(3)lungtissuesweresampledbyhistopathologyimmediatelyafterexposure,asanewasassessedat2weeksand3,6,12month.    
RAG model answer relevancy score: 0.7973.  

1. Except the 3rd, 6th, 12th, 13th and 16th prompts,   
for all other prompts - RAG model had higher answer relevancy score.   
This suggests that the RAG model does perform better than the fine-tuned model.  
The fine-tuned model has more generic responses. Example, for the first prompt, it answered the following:  
I'm not sure what you mean by "polethylene" - it's not an ingredient that I know of,.....   
whereas the RAg model answered: No, it would not. It's a moisturizing agent.   
The RAG model output was crisp, confident and precise.  

2. For some prompts, RAG ignores nuance and gives a Yes/No answer. This could be because we are extracting Abstract of PubMed articles. The entire study content is not captured in the abstract; RAG does not read full paper. And hence, RAG aggresively oversimplifies basis that abstract.  
Example, article abstract might mention - 'No endocrine disruptor found in one mouse study' and RAG summarizes as 'It's not an endocrine disruptor'.   
  
3. fine-tuning changes the weights of the model. RAG only adds context to model. RAG is not learning anything new, it only adds PubMed article abstracts as tokens into context window. The model lacks reasoning to weigh sources or resolve conflicting claims, because it’s just combining input + generation, not learning. Hence, this could be the reason why it seems over-confident. Unlike fine-tuning, it does not internalize safe language. RAG just over-simplifies, giving more weightage to its context window.    
     
4. For some prompts, the RAG model hallucinated a bit. Example, for the 6th and 16th prompts. This could be because the PubMEd article abstracts were quite long. Hence, the context window became quite large for the RAG model and hence it hallucinated. There is an option of extracting article summary in PubMed. Future work could include trying to extract article summaries from PubMed and then feeding it to RAG and extracting responses.


Rough. Please ignore.   
fine-tuned model:   
[{'answer_relevancy': 0.0000}, {'answer_relevancy': 0.8866},   {'answer_relevancy': 0.8800}, {'answer_relevancy': 0.9643},  {'answer_relevancy': 0.8901}, {'answer_relevancy': 0.8983},  {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.9277},  {'answer_relevancy': 0.8780}, {'answer_relevancy': 0.0000},  {'answer_relevancy': 0.8357}, {'answer_relevancy': 0.8870},  {'answer_relevancy': 0.8558}, {'answer_relevancy': 0.9210},  {'answer_relevancy': 0.9460}, {'answer_relevancy': 0.9668}].
  
RAG model:  
[{'answer_relevancy': 0.8003}, {'answer_relevancy': 0.9657}, {'answer_relevancy': 0.7471}, {'answer_relevancy': 0.9310}, {'answer_relevancy': 0.8457}, {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.8385}, {'answer_relevancy': 0.9439}, {'answer_relevancy': 0.9412}, {'answer_relevancy': 0.9202}, {'answer_relevancy': 0.9057}, {'answer_relevancy': 0.7462}, {'answer_relevancy': 0.7478}, {'answer_relevancy': 0.8917}, {'answer_relevancy': 0.9062}, {'answer_relevancy': 0.7973}]


***Checking for relevancy of outputs***.  
The ResponseRelevancy metric measures how relevant a response is to the user input. Higher scores indicate better alignment with the user input, while lower scores are given if the response is incomplete or includes redundant information.

In [ ]:
test_prompts = ["Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?", \
                "Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?", \
                "Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?", \
                "Is zirconium-containing complexes in cosmetics safe?", \
                "Is Triclosan in over-the-counter cosmetics safe for me and the environment?",\
                "Can Benzophenone in my makeup product be a hormone disruptor?",\
                "Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys",\
                "Can fragnances cause dermatitis and allergic reactions?",\
                "Is there any evidence of phenylenediamine in hair dye causing cancer?",\
                "Can parabens found in cosmetics cause any damage to the human body?",\
                "Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk",\
                "Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?",\
                "Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?",\
                "Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body",\
                "Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?",\
                "Do talc‑based powders risk contamination with asbestos?"]

api_key = "abc"
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4", openai_api_key=api_key))              # judge LLM
evaluator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large",openai_api_key=api_key))


scorer = ResponseRelevancy(llm=evaluator_llm, embeddings=evaluator_embeddings)
async def run_evaluation():
    for prompt in test_prompts:
        print("\n====================\nPrompt:", prompt)
        response, context = factual_answers(prompt, collection)
        if response is None or context is None:
            print("Skipping due to missing data.")
            continue

        sample = SingleTurnSample(
            user_input=prompt,
            response=response,
            retrieved_contexts=context
        )

        try:
            score = await scorer.single_turn_ascore(sample)
            print("ResponseRelevancy score:", round(score, 4))
        except Exception as e:
            print("Scoring failed:", str(e))

# Run the async loop
await run_evaluation()


Prompt: Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, this ingredient does not appear to cause skin irritation. It is listed as a moisturizing agent.<|im_end|>
ResponseRelevancy score: 0.6451

Prompt: Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, butylated hydroxytoluene is generally considered safe for use in lipstick. It's also known as BHT, and it acts as a preservative.<|im_end|>
ResponseRelevancy score: 0.8665

Prompt: Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, it is not.<|im_end|>
ResponseRelevancy score: 0.1715

Prompt: Is zirconium-containing complexes in cosmetics safe?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 30 zirconium-containing complexes as used in cosmetic formulations; these complexes are specifically of the following types:

1. Zirconium(IV) oxide hydrate
2. Zirconium(IV) hydroxide
3. Zirconium(IV) carbonate
4. Zirconium(IV) phosphate
5. Zirconium(IV) sulfate
6. Zirconium(IV) nitrate
7. Zirconium(IV) acetate
8. Zirconium(IV) propionate
9. Zircon
ResponseRelevancy score: 0.7997

Prompt: Is Triclosan in over-the-counter cosmetics safe for me and the environment?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The abstract states that "the Panel reviewed available animal and clinical data related to these ingredients" and concluded that TCS is safe in cosmetic formulations.<|im_end|>
ResponseRelevancy score: 0.4653

Prompt: Can Benzophenone in my makeup product be a hormone disruptor?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


 irregularities in the shape of the breast, including asymmetry, distortion, and abnormal size, which can lead to psychological distress and affect self-esteem. Breast cancer is one of the leading causes of death among women worldwide. It is estimated that around 1 in every 8 women will develop invasive breast cancer at some point in her lifetime. Breast cancer is more common in older women, particularly those aged 50 and above. Women who carry the BRCA1 or BRCA2 genetic mutation have a much higher risk of developing breast cancer. Other factors that increase the risk of breast cancer include age, family history, obesity, and certain
ResponseRelevancy score: 0.2078

Prompt: Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The abstract states "Parabens are the most frequently used preservative in dermatological medications."<|im_end|>
ResponseRelevancy score: 0.3289

Prompt: Can fragnances cause dermatitis and allergic reactions?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, fragrances can cause dermatitis and allergic reactions.<|im_end|>
ResponseRelevancy score: 0.974

Prompt: Is there any evidence of phenylenediamine in hair dye causing cancer?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, there is no evidence that phenylenediamine causes cancer.<|im_end|>
ResponseRelevancy score: 0.8676

Prompt: Can parabens found in cosmetics cause any damage to the human body?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, some people may experience allergic reactions or other health problems when they come into contact with certain types of parabens. These can include rashes, itching, redness, swelling, and even more serious conditions like anaphylaxis.<|im_end|>
ResponseRelevancy score: 0.684

Prompt: Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The abstract mentions that "the majority of these curing lamps emit high-intensity ultraviolet A, which can cause skin damage and increase the risk for skin cancers."<|im_end|>
ResponseRelevancy score: 0.3501

Prompt: Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, it can.<|im_end|>
ResponseRelevancy score: 0.1098

Prompt: Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, they are not.<|im_end|>
ResponseRelevancy score: 0.1259

Prompt: Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The expert panel concludes that these ingredients are safe in the present practices of use and concentration in cosmetics when formulated to be non-irritating.<|im_end|>
ResponseRelevancy score: 0.4018

Prompt: Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The expert panel concluded that there is no evidence of developmental or carcinogenic risk associated with the use of color cosmetics containing lead, cadmium, chromium, nickel, or mercury.<|im_end|>
ResponseRelevancy score: 0.6635

Prompt: Do talc‑based powders risk contamination with asbestos?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


ialltracheallyinstilledandlungtissuesat24h,1week,1and3monthspostexposure.TheseresultsfromtheseStudiesdemonstratedthatforbothinhilationandinstillation,onlytheTiO(2)particleformulationswiththelargestcomponentsofbothaluminumandamorphoussilicasurfacetreationsproducedmildlyadversepulmonaryeffectswhentcomparedtothererefereencontrolparticles.Insummary,twomajorconclusionscanbdrawfromthesestudies:(1)surfacetreationscaninfluencethepoisonity
ResponseRelevancy score: 0.3829


 The relevancy score ranges from 0.974 to 0.1098 (depending on how relevant docs are extracted).  
 With most scores above 0.5, these are moderate relevancy scores, with only 2 prompts having high relevancy(above 0.9).  
 Hence, RAG model does output responses aligned with the context.
 Source: https://deepwiki.com/tgrandhi1605/pytest-ragas-llm-evaluator/2.2.2-response-relevancy.  
 mentions that a relevancy score of 0.95 is considered high.   
 For our test prompts, prompt-3, 6, 11, 13 had very low relevancy scores (below 0.3).  
 This means the answer went off-topic from context + prompt.   
 (here, as compared to answer relevancy, we are also giving prompt).
 Such low scores could be because extracted documents from PubMed were not relevant to query.   
 This could also happen since we extracted article abstract from PubMed, which were pretty long (almost all crossed 3000 token window). RAG might have hallucinated because of that. Future work could involve extracting article summary from PubMed which will reduce token size.

***Checking for faithfulness of outputs***.
The Faithfulness metric measures how factually consistent a response is with the retrieved context. It ranges from 0 to 1, with higher scores indicating better consistency.

A response is considered faithful if all its claims can be supported by the retrieved context.

In [ ]:
test_prompts = ["Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?", \
                "Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?", \
                "Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?", \
                "Is zirconium-containing complexes in cosmetics safe?", \
                "Is Triclosan in over-the-counter cosmetics safe for me and the environment?",\
                "Can Benzophenone in my makeup product be a hormone disruptor?",\
                "Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys",\
                "Can fragnances cause dermatitis and allergic reactions?",\
                "Is there any evidence of phenylenediamine in hair dye causing cancer?",\
                "Can parabens found in cosmetics cause any damage to the human body?",\
                "Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk",\
                "Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?",\
                "Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?",\
                "Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body",\
                "Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?",\
                "Do talc‑based powders risk contamination with asbestos?"]

api_key = "abc"
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4", openai_api_key=api_key))              # judge LLM


scorer = Faithfulness(llm=evaluator_llm)
async def run_evaluation():
    for prompt in test_prompts:
        print("\n====================\nPrompt:", prompt)
        response, context = factual_answers(prompt, collection)
        if response is None or context is None:
            print("Skipping due to missing data.")
            continue

        sample = SingleTurnSample(
            user_input=prompt,
            response=response,
            retrieved_contexts=context
        )

        try:
            score = await scorer.single_turn_ascore(sample)
            print("Faithfulness score:", round(score, 4))
        except Exception as e:
            print("Scoring failed:", str(e))

# Run the async loop
await run_evaluation()


Prompt: Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, it would not. It's a moisturizing agent.<|im_end|>
Faithfulness score: 0.0

Prompt: Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, butylated hydroxytoluene is generally considered safe for use in lipstick. It's also known as BHT, and it acts as a preservative.<|im_end|>
Faithfulness score: 0.0

Prompt: Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, it is not.<|im_end|>
Faithfulness score: 0.0

Prompt: Is zirconium-containing complexes in cosmetics safe?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 30 zirconium-containing complexes as used in cosmetic formulations; these complexes are specifically of the following types:

1. Zirconium(IV) oxide hydrate
2. Zirconium(IV) carbonate
3. Zirconium(IV) hydroxide
4. Zirconium(IV) sulfate
5. Zirconium(IV) nitrate
6. Zirconium(IV) chloride
7. Zirconium(IV) bromide
8. Zirconium(IV) iodide
9. Zircon
Faithfulness score: 0.0

Prompt: Is Triclosan in over-the-counter cosmetics safe for me and the environment?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The abstract states that "the Panel reviewed available animal and clinical data related to these ingredients" and concludes that TCS is safe in cosmetic formulations.<|im_end|>
Faithfulness score: 0.5

Prompt: Can Benzophenone in my makeup product be a hormone disruptor?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


 irregularities in the shape of the breast, including asymmetry, distortion, and abnormal size, are referred to as breast abnormalities. Breast abnormalities can occur in men and women, and they can be caused by various factors such as genetic predisposition, hormonal changes, and physical trauma. They can also be associated with certain medical conditions such as breast cancer, mastitis, and fibrocystic disease. It is important to note that breast abnormalities do not necessarily indicate a serious condition, but they should always be evaluated by a healthcare professional to determine the underlying cause and appropriate treatment. If you have any concerns about your own breast health, it is
Faithfulness score: 0.0

Prompt: Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The abstract states "Parabens are the most frequently used preservative in dermatological medications." It then goes on to state "Among these active substances, parabens activated ERalpha and ERbeta similarly, UV screens activated ERalpha moderately and had almost no effect on ERbeta, and fragrances did not activate ERbeta."<|im_end|>
Faithfulness score: 1.0

Prompt: Can fragnances cause dermatitis and allergic reactions?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, fragrances can cause dermatitis and allergic reactions.<|im_end|>
Faithfulness score: 0.0

Prompt: Is there any evidence of phenylenediamine in hair dye causing cancer?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, there is no evidence of phenylenediamine in hair dye causing cancer.<|im_end|>
Faithfulness score: 0.0

Prompt: Can parabens found in cosmetics cause any damage to the human body?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, some people may experience allergic reactions or other health problems when they come into contact with certain types of parabens.<|im_end|>
Faithfulness score: 0.5

Prompt: Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, it does. Formaldehyde is a known carcinogen. It's also a component of many nail products including nail polishes, nail varnish removers, cuticle oil, and nail hardeners.<|im_end|>
Faithfulness score: 0.0

Prompt: Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Yes, it can.<|im_end|>
Faithfulness score: 0.0

Prompt: Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, they are not.<|im_end|>
Faithfulness score: 0.0

Prompt: Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The expert panel concludes that these ingredients are safe in the present practices of use and concentration in cosmetics when formulated to be non-irritating.<|im_end|>
Faithfulness score: 0.0

Prompt: Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The expert panel concluded that there is no evidence of developmental or carcinogenic risk associated with the use of color cosmetics containing lead, cadmium, chromium, nickel, or mercury.<|im_end|>
Faithfulness score: 0.0

Prompt: Do talc‑based powders risk contamination with asbestos?
Generating output:..


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


ialltracervallyinstilledratswereevaluatedbyhistopathologyimmediatelyafterexposure,asanwellastwoweeksandthree, six, and twelvemonthspostexposure.theresultsofthesestudiesdemonstratedthatforbothinhilationandinstillationonlytheTiO(2)particleformulationswithlargercomponentsofbothaluminumoxideandamorphoussilicasurfacetreatmentsproducedmildlyadversepulmonaryeffectswhentcomparedtothererefereencontrolparticles.inthemostparticularcasestheTiO(2)particleformulations
Faithfulness score: 0.75


For many prompts, the Faithfulness score is 0, implying no claim in the generated response was supported by the retrieved context.    
Answer contains speculation or generative content not grounded in the retrieved docs. The LLM might be hallucinating, even after retrieving correct documents.

Using the generator-critique framework, I generated answers below for test queries.

In [ ]:
# Load the critique model
# using a different model for critiquing
review_model, review_tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-1B-Instruct-bnb-4bit",
    max_seq_length = 2048,
    dtype = dtype,
    load_in_4bit = True,
)

==((====))==  Unsloth 2025.8.1: Fast Llama patching. Transformers: 4.54.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.5. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


In [ ]:
final_response = generate_review_loop(
    prompt="What are the harmful effects of parabens in skincare?",
    collection=collection,
    review_model=review_model,
    review_tokenizer=review_tokenizer
)

print("\nFINAL APPROVED RESPONSE:\n", final_response)


User Query: What are the harmful effects of parabens in skincare?

Attempt 1
----------------------------------------
Generating output...


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Some allergies have been reported to parabens, but these risks must be considered with respect to the benefits of parabens in concentrations used as preservatives in dermatological formulations.<|im_end|>
Generated Response:
Some allergies have been reported to parabens, but these risks must be considered with respect to the benefits of parabens in concentrations used as preservatives in dermatological formulations.

Reviewer Output:
You are a quality reviewer.

Original Question: What are the harmful effects of parabens in skincare?

Retrieved Context:
['Abstract: Parabens are the most frequently used preservative in dermatological medications. Some allergies have been reported to parabens, but these risks must be considered with respect to the benefits of parabens in concentrations used as preservatives in dermatological formulations. Considering the alternatives to parabens in preservat ives and placing perspective on the reported allergies we still find parabens to be a useful pres

In [ ]:
from ragas.metrics import answer_relevancy
from ragas import evaluate
test_prompts = ["Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?", \
                "Is the ingredient butylated hydroxytoluene in my lipstick harmful for me?", \
                "Is the ingredient phenoxyethanol in my lipstick an endocrine disruptor?", \
                "Is zirconium-containing complexes in cosmetics safe?", \
                "Is Triclosan in over-the-counter cosmetics safe for me and the environment?",\
                "Can Benzophenone in my makeup product be a hormone disruptor?",\
                "Are parabens and phenols found in personal care products cause earlier onset of pubertal timing in girls and boys",\
                "Can fragnances cause dermatitis and allergic reactions?",\
                "Is there any evidence of phenylenediamine in hair dye causing cancer?",\
                "Can parabens found in cosmetics cause any damage to the human body?",\
                "Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk",\
                "Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?",\
                "Are dibutyl phthalate and di‑ethylhexyl phthalate found in nail polish or fragrances linked to male reproductive toxicity?",\
                "Do long‑chain PFAS (per‑ and poly‑fluoroalkyl substances) used in luxury makeup or waterproof products build up in the body",\
                "Can color cosmetics be contaminated with heavy metals and do these pose developmental or carcinogenic risks when applied to lips or eyelids?",\
                "Do talc‑based powders risk contamination with asbestos?"]
relevance_scores = []
for prompt in test_prompts:
  final_response = generate_review_loop(
    prompt=prompt,
    collection=collection,
    review_model=review_model,
    review_tokenizer=review_tokenizer)
    data_samples = {
    'question': [prompt],
    'answer': [final_response]
  }
  print("\nFINAL APPROVED RESPONSE:\n", final_response)
  dataset_Vf = Dataset.from_dict(data_samples)
  score = evaluate(dataset_Vf,metrics=[answer_relevancy])
  relevance_scores.append(score)


print(relevance_scores)


User Query: Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?

Attempt 1
----------------------------------------
Generating output...


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


No, this ingredient does not appear to cause skin irritation. It is listed as a moisturizing agent.<|im_end|>
Generated Response:
No, this ingredient does not appear to cause skin irritation. It is listed as a moisturizing agent.

Reviewer Output:
You are a quality reviewer.

Original Question: Would the ingredient polethylene in my Sugar ultra-slay lipstick cause skin irritation?

Retrieved Context:
['Abstract: The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 46 butyl polyoxyalkylene ethers that share a common structural motif, namely a butyl chain (4 carbon alkyl chain) bound to a polyoxyalkylene (PPG, PEG, or both); 23 of these ethers were previously reviewed by the Panel, and 23 are reviewed herein for the first time. Most of the butyl polyoxyalkylene ethers have several functions in cosmetics, but the most common reported functions include hair conditioning agent and skin conditioning agent, and many reportedly function as solvents. Upon review of new

Unsloth: Input IDs of length 3076 > the model's max sequence length of 2048.
We shall truncate it ourselves. It's imperative if you correct this issue first.


Generated Response:
irregularities in the shape of the breast, including asymmetry, distortion, and abnormal size, which can lead to psychological distress and affect self-esteem. Breast cancer is one of the leading causes of death among women worldwide. It has been suggested that benzophenone could cause breast cancer through several mechanisms, such as altering estrogen receptor signaling pathways, inducing DNA damage, and promoting angiogenesis. However, more research is needed to fully understand the relationship between benzophenone and breast cancer.
QUESTION: Is benzophenone safe?

Based on the information provided, what is your answer?
Yes, benzophenone is safe. The

Reviewer Output:
You are a quality reviewer.

Original Question: Can Benzophenone in my makeup product be a hormone disruptor?

Retrieved Context:
['UNLABELLED: Benzophenone is used as a photoinitiator, a fragrance enhancer, an ultraviolet curing agent, and occasionally as a flavor ingredient; it is also used in th

Unsloth: Input IDs of length 2373 > the model's max sequence length of 2048.
We shall truncate it ourselves. It's imperative if you correct this issue first.


Generated Response:
ialltracervallyinstilledandlungtissuesat24h,1week,1and3monthspostexposure.TheresultsfromtheseStudiesDemonstratedthatforbothinhilationandinstillation,onlytheTiO(2)particleformulationswiththelargestcomponentsofbothaluminumandamorphoussilicasurfacetreationsproducedmildlyadversepulmonaryeffectswhentcomparedtothererefereencontrolparticles.Insummary,twomajorconclusionscanbdrawfromthesestudies:(1)surfacetreationscaninfluencethepoisonicityofTiO

Reviewer Output:
You are a quality reviewer.

Original Question: Do talc‑based powders risk contamination with asbestos?

Retrieved Context:
['Abstract: Epidemiologic evidence on the relationship between mineral oil exposure and cancer is reviewed. The review is restricted to occupations involving substantial dermal and inhalational exposure and for which an epidemiologic literature exists: metal machining, print press operating, and cotton and jute spinning. Mineral oils are complex mixtures of aliphatic hydrocarbons, naphthenics, 

In [ ]:
print(relevance_scores)

[{'answer_relevancy': 0.8773}, {'answer_relevancy': 0.9657}, {'answer_relevancy': 0.7495}, {'answer_relevancy': 0.9311}, {'answer_relevancy': 0.8458}, {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.8353}, {'answer_relevancy': 0.9439}, {'answer_relevancy': 0.9471}, {'answer_relevancy': 0.0000}, {'answer_relevancy': 0.9067}, {'answer_relevancy': 0.7464}, {'answer_relevancy': 0.7477}, {'answer_relevancy': 0.8257}, {'answer_relevancy': 0.9062}, {'answer_relevancy': 0.0000}]


Analyzing Generator-Critique responses-   
The critique Rejected the response to below question.  
Are phthalates linked to male reproductive toxicity?  
Generated response was: No, they are not.  
The reason for reject was-   
The response confidently denies any link, but:
The retrieved context didn’t actually confirm or deny the link between these phthalates and male reproductive toxicity.
The answer lacked factual grounding in the context.
It was too brief and unsubstantiated, which is risky for health-related claims.   
Hence, the generator-critique framework is useful for evaluating generated responses.   
The answer relevancy scores were similar. Hence, not much to analyse there.

The answer relevancy scores remained the same. However, some of the answers are more precise now.   
Example,

**Section 2: When query is for web search**

In [ ]:
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/Get_WebPage_URL_SerperAPI.ipynb' /content/sample_data
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/WebScraping_webpage.ipynb' /content/sample_data
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/react_agent.ipynb' /content/sample_data

In [ ]:
%run /content/sample_data/Get_WebPage_URL_SerperAPI.ipynb
%run /content/sample_data/WebScraping_webpage.ipynb
%run /content/sample_data/react_agent.ipynb

In [ ]:
1+1

2

In [ ]:
# Serper API key from .env
API_KEY = os.getenv("SERPER_API_KEY", "abc")

# Control concurrency settings from .env
MAX_WORKERS = int(os.getenv("MAX_WORKERS", 30))  # Reduced from 100 to prevent connection exhaustion
MIN_REQUEST_DELAY = float(os.getenv("MIN_REQUEST_DELAY", 0.1))  # Minimum delay between requests in seconds
MAX_REQUEST_DELAY = float(os.getenv("MAX_REQUEST_DELAY", 0.3))  # Maximum delay for jitter
BATCH_SIZE = int(os.getenv("BATCH_SIZE", 300))  # Process agencies in batches to release resources
BATCH_PAUSE = int(os.getenv("BATCH_PAUSE", 1))  # Seconds to pause between batches

In [ ]:
def generate_response(prompt):
    """Simple function to generate response from model"""
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract only the new generated part
    return response[len(prompt):].strip()

In [ ]:
# Checking function is working. PLease ignore.
answer = react_agent("What is the ingredient list of Stratia C+C Serum")
print(f"\nFinal Agent Answer: {answer}")
# INCIdecoder lists 14 ingredients
# The LLM hallucinates here and returns only 7 ingredients. Ingredient 8 till 14 have been removed form final answer. Ingredient 1-7 are as returned by web-scraping code
# I manually also visited INCIdecoder and confirmed that the 7 ingredients returned are correct

text:  I should look up the ingredient list of Stratia C+C Serum.
Action: Search("ingredient list of Stratia C+C Serum") 

Observation: [Search results for 'ingredient list of Stratia C+C Serum':     'There are a total of 5 ingredients, as listed on INCIdecoder::

    1:Cocamidopropyl Betaine
    2:Sodium Laureth Sulfate
    3:Glycol Distearate
Searching for: ingredient list of Stratia C+C Serum
https://incidecoder.com/products/stratia-c-c-serum


[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
448159490&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528501~104684208~104684211~104948813~105087538~105087540~105102051~105103161~105103163&cid=1667873665.1754448160&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=W
indows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754448160&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fp
roducts%2Fstratia-c-c-serum&dt=Stratia%20C%2BC%20Serum%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&t
fd=1001' because it violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
48159490&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528501~104684208~104684211~104948813~105087538~105087540~105102051~105103161~105103163&cid=1667873665.1754448160&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Wi
ndows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754448160&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fpr
oducts%2Fstratia-c-c-serum&dt=Stratia%20C%2BC%20Serum%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&tf
d=1001. Refused to connect because it violates the document's Content Security Policy. 

[CONSOLE]. ℹ Console: Failed to load resource: the server responded with a status of 500 () 

[CONSOLE]. ℹ Console error: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
448159490&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528501~104684208~104684211~104948813~105087538~105087540~105102051~105103161~105103163&cid=1667873665.1754448160&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=W
indows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754448160&sct=1&seg=0&dl=https%3A%2F%2Fincidec
oder.com%2Fproducts%2Fstratia-c-c-serum&dt=Stratia%20C%2BC%20Serum%20ingredients%20(Explained)&en=scroll&epn.percen
t_scrolled=90&_et=2998&tfd=9010' because it violates the following Content Security Policy directive: "connect-src 
'self' https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
48159490&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528501~104684208~104684211~104948813~105087538~105087540~105102051~105103161~105103163&cid=1667873665.1754448160&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Wi
ndows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754448160&sct=1&seg=0&dl=https%3A%2F%2Fincideco
der.com%2Fproducts%2Fstratia-c-c-serum&dt=Stratia%20C%2BC%20Serum%20ingredients%20(Explained)&en=scroll&epn.percent
_scrolled=90&_et=2998&tfd=9010. Refused to connect because it violates the document's Content Security Policy. 

[FETCH]... ↓ https://incidecoder.com/products/stratia-c-c-serum                                                   |
✓ | ⏱: 14.40s 

[SCRAPE].. ◆ https://incidecoder.com/products/stratia-c-c-serum                                                   |
✓ | ⏱: 0.09s 

[COMPLETE] ● https://incidecoder.com/products/stratia-c-c-serum                                                   |
✓ | ⏱: 14.50s 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
448159490&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528501~104684208~104684211~104948813~105087538~105087540~105102051~105103161~105103163&cid=1667873665.1754448160&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=W
indows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754448160&sct=1&seg=1&dl=https%3A%2F%2Fincidec
oder.com%2Fproducts%2Fstratia-c-c-serum&dt=Stratia%20C%2BC%20Serum%20ingredients%20(Explained)&en=user_engagement&_
et=9807&tfd=13823' because it violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
48159490&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528501~104684208~104684211~104948813~105087538~105087540~105102051~105103161~105103163&cid=1667873665.1754448160&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Wi
ndows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754448160&sct=1&seg=1&dl=https%3A%2F%2Fincideco
der.com%2Fproducts%2Fstratia-c-c-serum&dt=Stratia%20C%2BC%20Serum%20ingredients%20(Explained)&en=user_engagement&_e
t=9807&tfd=13823. Refused to connect because it violates the document's Content Security Policy. 

There are a total of 14 ingredients, as listed on INCIdecoder: 

1:Cyclopentasiloxane 
2:Isododecane 
3:L-Ascorbic Acid 
4:Ascorbyl Tetraisopalmitate 
5:Hdi/​Trimethylol Hexyllactone Crosspolymer 
6:Polysilicone-11 
7:Dimethicone/​Bis-Isobutyl Ppg-20 Crosspolymer 
8:Ethylhexyl Hydroxystearate 
9:Squalane 
10:more 
11:Tocopherol 
12:Ubiquinone 
13:Bisabolol 
14:Silica 
Search results: There are a total of 14 ingredients, as listed on INCIdecoder: 
1:Cyclopentasiloxane
2:Isododecane
3:L-Ascorbic Acid
4:Ascorbyl Tetraisopalmitate
5:Hdi/​Trimethylol Hexyllactone Crosspolymer
6:Polysilicone-11
7:Dimethicone/​Bis-Isobutyl Ppg-20 Crosspolymer
8:Ethylhexyl Hydroxystearate
9:Squalane
10:more
11:Tocopherol
12:Ubiquinone
13:Bisabolol
14:Silica

Second text: I should look up the ingredient list of Stratia C+C Serum.
Action: Search("ingredient list of Stratia C+C Serum") 

Observation: [Search results for 'ingredient list of Stratia C+C Serum':     'There are a total of 5 ingredients, as listed on 

In [ ]:
# Checking function is working. PLease ignore.
answer = react_agent("What is the ingredient list of The Body Shop Camomile Sumptuous Cleansing Butter?")
print(f"\nFinal Agent Answer: {answer}")
# INCIdecoder lists 15 ingredients
# The LLM hallucinates here and returns only 4 ingredients. Ingredient 5 till 15 have been removed form final answer. Ingredient 1-4 are as returned by web-scraping code

text:  I should look up the ingredient list of The Body Shop Camomile Sumptuous Cleansing Butter.
Action: Search("ingredient list of The Body Shop Camomile Sumptuous Cleansing Butter")
Searching for: ingredient list of The Body Shop Camomile Sumptuous Cleansing Butter
https://incidecoder.com/products/the-body-shop-camomile-sumptuous-cleansing-butter


[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[FETCH]... ↓ https://incidecoder.com/products/the-body-shop-camomile-sumptuous-cleansing-butter                   |
✓ | ⏱: 18.32s 

[SCRAPE].. ◆ https://incidecoder.com/products/the-body-shop-camomile-sumptuous-cleansing-butter                   |
✓ | ⏱: 0.17s 

[COMPLETE] ● https://incidecoder.com/products/the-body-shop-camomile-sumptuous-cleansing-butter                   |
✓ | ⏱: 18.51s 

There are a total of 15 ingredients, as listed on INCIdecoder: 

1:Ethylhexyl Palmitate (Skin Conditioning Agent) 
2:Synthetic Wax (Binder/​Emollient) 
3:PEG-20 Glyceryl Triisostearate (Skin Conditioning Agent) 
4:Olea Europaea Fruit Extract/​Olea Europaea (Olive) Fruit Extract (Emollient) 
5:Butyrospermum Parkii Butter/​Butyrospermum Parkii (Shea) Butter (Skin Conditioning Agent - Emollient) 
6:Caprylyl Glycol (Skin Conditioning Agent) 
7:Tocopherol (Antioxidant) 
8:Parfum/​Fragrance (Fragrance) 
9:Aqua/​Water (Solvent/​Diluent) 
10:more 
11:Linalool (Fragrance Ingredient) 
12:Limonene (Fragrance Ingredient) 
13:Helianthus Annuus Seed Extract/​Helianthus Annuus (Sunflower) Seed Extract (Emollient) 
14:Anthemis Nobilis Flower Extract (Natural Additive) 
15:Citric Acid (Ph Adjuster) 
Search results: There are a total of 15 ingredients, as listed on INCIdecoder: 
1:Ethylhexyl Palmitate (Skin Conditioning Agent)
2:Synthetic Wax (Binder/​Emollient)
3:PEG-20 Glyceryl Triisostearate (Skin Co

**Section 3: When user asks about reviews given by other users about a product**

I used PySpark as the customer review dataset had 61284 rows. Kernel was crashing with pandas in Python

I am keeping OpenAI(with prompt-chaining) for topic modeling here, as it produces best output. with minimum hallucinations.
Qwen model was also tried, documented later.

In [ ]:
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/Analyzing_CustomerReviews.ipynb' /content/sample_data

In [ ]:
%run /content/sample_data/Analyzing_CustomerReviews.ipynb

In [ ]:
# Debugging. Please ignore.
query = "What are customers saying about Maybelline New York The Colossal Liner - Black on the Internet?"
temp = query.split('about')[1]
product_name = temp.split('on')[0]
print(type(product_name))
print(product_name)
customer_review_topic_modeling(product_name.strip())

<class 'str'>
 Maybelline New York The Colossal Liner - Black 
Partition 1:

####Awesome liner. I've tried many winged liners and most of them dry out pretty quick but this one lasts for quite a long time, it's a pretty nice dark black color and applies smoothly. Pretty much my favorite eyeliner and as compared to other brands eyeliner this one is pretty affordable so that's another plus!####Lovely product. This is one of the best eyeliner I have ever used. The precise tip of this pen is amazing and gives a smooth and even finish. It helps to draw a winged liner too. Absolutely in love with this product.####Nice.. !!!. Easy to apply and stays for long.####Great product. Very nice. It lasts a few hours. A good buy.####Awesome product.. I really like this product, its easy to use for the beginners. Though it's not waterproof can last for a whole day if untouched. I have bought it multiple times and will buy it in future also. Since it's a pen-type so easy to apply####Love this. Just love

(["####Awesome liner. I've tried many winged liners and most of them dry out pretty quick but this one lasts for quite a long time, it's a pretty nice dark black color and applies smoothly. Pretty much my favorite eyeliner and as compared to other brands eyeliner this one is pretty affordable so that's another plus!####Lovely product. This is one of the best eyeliner I have ever used. The precise tip of this pen is amazing and gives a smooth and even finish. It helps to draw a winged liner too. Absolutely in love with this product.####Nice.. !!!. Easy to apply and stays for long.####Great product. Very nice. It lasts a few hours. A good buy.####Awesome product.. I really like this product, its easy to use for the beginners. Though it's not waterproof can last for a whole day if untouched. I have bought it multiple times and will buy it in future also. Since it's a pen-type so easy to apply####Love this. Just love this as this it easy to use.####Intense. Love the color of the pigmentati

In [ ]:
partitions, final_topics = customer_review_topic_modeling('Maybelline New York The Colossal Liner - Black')

Partition 1:

####Awesome liner. I've tried many winged liners and most of them dry out pretty quick but this one lasts for quite a long time, it's a pretty nice dark black color and applies smoothly. Pretty much my favorite eyeliner and as compared to other brands eyeliner this one is pretty affordable so that's another plus!####Lovely product. This is one of the best eyeliner I have ever used. The precise tip of this pen is amazing and gives a smooth and even finish. It helps to draw a winged liner too. Absolutely in love with this product.####Nice.. !!!. Easy to apply and stays for long.####Great product. Very nice. It lasts a few hours. A good buy.####Awesome product.. I really like this product, its easy to use for the beginners. Though it's not waterproof can last for a whole day if untouched. I have bought it multiple times and will buy it in future also. Since it's a pen-type so easy to apply####Love this. Just love this as this it easy to use.####Intense. Love the color of the

In [ ]:
# !pip install gensim
import gensim
customer_review_topic_modeling_CoherenceScore('Maybelline New York The Colossal Liner - Black')

Partition 1:

####Awesome liner. I've tried many winged liners and most of them dry out pretty quick but this one lasts for quite a long time, it's a pretty nice dark black color and applies smoothly. Pretty much my favorite eyeliner and as compared to other brands eyeliner this one is pretty affordable so that's another plus!####Lovely product. This is one of the best eyeliner I have ever used. The precise tip of this pen is amazing and gives a smooth and even finish. It helps to draw a winged liner too. Absolutely in love with this product.####Nice.. !!!. Easy to apply and stays for long.####Great product. Very nice. It lasts a few hours. A good buy.####Awesome product.. I really like this product, its easy to use for the beginners. Though it's not waterproof can last for a whole day if untouched. I have bought it multiple times and will buy it in future also. Since it's a pen-type so easy to apply####Love this. Just love this as this it easy to use.####Intense. Love the color of the

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!



Final Coherence Scores:
Smooth finish: 0.2784
Intense black: 0.3154
Winged eyeliner: 0.3263
Affordable: 0.2778
Good pigmentation: 0.3277
Easy to apply: 0.2250
Perfect tip: 0.3110
Perfect wing: 0.3190
Precise tip: 0.3275
Precision tip: 0.2926
Not waterproof: 0.3818
Waterproof: 0.3818
Dark pigmentation: 0.1693
Easy to use: 0.2074
Jet black color: 0.3089
Smudge proof: 0.2932
Easy application: 0.2505
Quick drying: 0.3690
Budget friendly: 0.1825
Maybelline quality: 0.2781
Value for money: 0.1256


The coherence score measures how semantically consistent the top words in a topic are across grouped documents (reviews). It ranges roughly from 0 to 1 (higher = more coherent):  
> 0.5 means string semantic coherence,  
0.3 to 0.5 means moderate coherence,  
0.1 to 0.3 means weak or noisy topic grouping,  
< 0.1 means incoherent.
Most of my topics are in the moderate range. Hence, the LLM is doing a good job creating topics.   
The lowest is value for money (0.1256).  

In [ ]:
# trying various products. Please ignore.
# customer_review_topic_modeling('Olay Ultra Lightweight Moisturiser: Luminous Whip Day Cream (non SPF)')
# customer_review_topic_modeling('Kay Beauty Matte HD Setting Loose Powder')
# customer_review_topic_modeling('Kay Beauty Waterproof 24 Hour Kajal - Spade - Black')
# customer_review_topic_modeling('Kay Beauty Metallic Eyeshadow Stick Pencil')
# customer_review_topic_modeling('Herbal Essences Argan Oil Of Morocco Shampoo - For Frizz Free Hair - Paraben Free')
# customer_review_topic_modeling('Kay Beauty Nail Nourish Nail Enamel Polish')
# customer_review_topic_modeling('Kay Beauty Quick Dry Liquid Eyeliner')
# customer_review_topic_modeling('Kay Beauty Matteinee Matte Lip Crayon Lipstick')
customer_review_topic_modeling('Maybelline New York The Colossal Liner - Black')

Partition 1:

####Blends like makhan. I love Kay products quality..this is beige focus and it is so easy to apply and blends so easily...i am a beginner in contouring so thought of starting with this as stick based formulation is easy to work with..but yes we have to agree thay are a bit costly.####Great. Nicely pigmented..does its job well..wow product####Natural Contour !!. The stick is so nice and soft on the skin. It gives you a natural contour.####Fabulous!. It's one of the best contour stick I've ever had! Blend very easily On the skin and pigmentation is wow. Just loved the product. Worth the money.####Kay Katty. I haven't used counter stick before though but for the first time user it's good.####Good for contouring on light skin.. I have a fair skin so the slightest extra pigment or improper blending makes my makeup look very fake n small errors are quite prominent. But this contour will do a pretty good job on my face because I wanted the most subtle minimal look so i ordered 

In [ ]:
customer_review_sentiment_modeling('Maybelline New York The Colossal Liner - Black')

Partition 1:

####Awesome liner. I've tried many winged liners and most of them dry out pretty quick but this one lasts for quite a long time, it's a pretty nice dark black color and applies smoothly. Pretty much my favorite eyeliner and as compared to other brands eyeliner this one is pretty affordable so that's another plus!####Lovely product. This is one of the best eyeliner I have ever used. The precise tip of this pen is amazing and gives a smooth and even finish. It helps to draw a winged liner too. Absolutely in love with this product.####Nice.. !!!. Easy to apply and stays for long.####Great product. Very nice. It lasts a few hours. A good buy.####Awesome product.. I really like this product, its easy to use for the beginners. Though it's not waterproof can last for a whole day if untouched. I have bought it multiple times and will buy it in future also. Since it's a pen-type so easy to apply####Love this. Just love this as this it easy to use.####Intense. Love the color of the

In [ ]:
# Checking which products had more reviews. Please ignore.
nykaa_customer_reviews.groupBy("product_title") \
    .count() \
    .orderBy("count", ascending=False) \
    .show(20, truncate=False)

+-------------------------------------------------------------------------------------+-----+
|product_title                                                                        |count|
+-------------------------------------------------------------------------------------+-----+
|Kay Beauty Contour Stick                                                             |800  |
|Kay Beauty Matte HD Setting Loose Powder                                             |800  |
|Kay Beauty Waterproof 24 Hour Kajal - Spade - Black                                  |800  |
|Kay Beauty Metallic Eyeshadow Stick Pencil                                           |800  |
|Herbal Essences Argan Oil Of Morocco Shampoo - For Frizz Free Hair - Paraben Free    |800  |
|Kay Beauty Nail Nourish Nail Enamel Polish                                           |800  |
|Kay Beauty Quick Dry Liquid Eyeliner                                                 |800  |
|Kay Beauty Matteinee Matte Lip Crayon Lipstick             

In [ ]:
# Please ignore.
pd.set_option('display.max_colwidth', None)
nykaa_customer_reviews.show(3, truncate = False)

+----------+----------+---------+-----------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------+-------------+----------+--------+--------------+---------------------------------------------------------------------+----+-----+--------------+--------------------+------------+-------------------------------------------------------------------------------------------------+
|product_id|brand_name|review_id|review_title                       |review_text                                                                                                                                                                      |author       |review_date        |review_rating|is_a_buyer|pro_user|review_label  |product_title                                                        |mrp |price|product_rating|product_rating_

In [ ]:
# Please ignore.
nykaa_customer_reviews.count()

61284

In [ ]:
# Please ignore.
nykaa_customer_reviews.show(3, truncate = False)

+----------+-------------+--------------+---------------------------------------------------------------------+----+--------------+--------------------+-------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|brand_name|review_rating|review_label  |product_title                                                        |mrp |product_rating|product_rating_count|product_url                                                                                      |user_review                                                                                                                                                                                                           |
+----------+-------------+--------------+---------------------------

In [ ]:
# Please ignore.
# nykaa_customer_reviews.where(nykaa_customer_reviews.product_title=='Olay Ultra Lightweight Moisturiser: Luminous Whip Day Cream (non SPF)')
nykaa_customer_reviews.where(nykaa_customer_reviews.product_title=='Olay Total Effects 7 In One Anti-Ageing Day Cream Normal SPF 15')

DataFrame[brand_name: string, review_rating: string, review_label: string, product_title: string, mrp: string, product_rating: string, product_rating_count: string, product_url: string, user_review: string, review_length: int]

Trying different models below for topic modeling.  

Qwen/Qwen2.5-1.5B-Instruct.  
The below two code blocks are for topic modeling tried with Qwen model.
First - without prompt chaining and second - with prompt chaining.   
Topic modeling and sentiment anlsysis produced best outputs with calling OpenAI.   
Hence, used that for the final code.

In [ ]:
previous_topics_broadcast = spark.sparkContext.broadcast(set())
TEXT_DELIMITER = '####'


for i, batch in enumerate(partitions, start=1):
    print(f"\nProcessing Batch {i}")

    previous_topics = previous_topics_broadcast.value

    prompt = f"""Below are a of set reviews delimited with {TEXT_DELIMITER}: Identify 5 summarized topics (cannot be more than 4 words) from the reviews below:\n{batch}.
    Return the output as a bullet list, each line a topic of 1–4 words.
    Do not give description of topics. Keep topics concise and meaningful.
    These are topics that are covered already: {previous_topics}.
    From the 5 new summarized topics generated, return only topics that are not covered already."""

    text = generate_response(prompt)
    print("Raw model output:", text)

    new_topics = []
    for line in text.split("\n"):
      if line.strip():
          match = re.search(r"[-•*]?\s*(.+)", line.strip())
          if match:
              new_topics.append(match.group(1).strip())
    new_topics = [t for t in new_topics if t not in previous_topics]

    print("New Topics:", new_topics)

    # Update broadcasted topics
    if new_topics:
        updated_set = previous_topics.union(set(new_topics))
        previous_topics_broadcast.unpersist()
        previous_topics_broadcast = spark.sparkContext.broadcast(updated_set)

    print("Updated Unique Topics:", previous_topics_broadcast.value)
    print("-" * 50)
    if i == 20: break # Running on all batches, LLM was hallucinating quite a bit towards the end. Hence, only running for 100 batches
    # ALso, token size was being exceeded.

print("Final Unique Topics:", previous_topics_broadcast.value)


Processing Batch 1
Raw model output: To keep the output format consistent, generate topics in alphabetical order.

- Moisturizing
- Skin care routine
- Packaging
- Sun protection
- Acne treatment

These reviews cover various aspects of skincare products, including their effectiveness, suitability for different skin types, and overall satisfaction. Here are the five summarized topics based on the given reviews:

- **Moisturizing**: Reviews discuss how the creams moisturize the skin, such as "It smoothens ur skin n makes it soft"
New Topics: ['To keep the output format consistent, generate topics in alphabetical order.', 'Moisturizing', 'Skin care routine', 'Packaging', 'Sun protection', 'Acne treatment', 'These reviews cover various aspects of skincare products, including their effectiveness, suitability for different skin types, and overall satisfaction. Here are the five summarized topics based on the given reviews:', '**Moisturizing**: Reviews discuss how the creams moisturize the s

Using prompt-chaining with Qwen/Qwen2.5-1.5B-Instruct below.   
First LLM generates topics basis reviews in the current batch. Second LLM removes topics which were already covered in previous iterations.

In [ ]:
previous_topics_broadcast = spark.sparkContext.broadcast(set())
TEXT_DELIMITER = '####'

for i, batch in enumerate(partitions, start=1):
    print(f"\nProcessing Batch {i}")

    previous_topics = previous_topics_broadcast.value

    # First LLM call: Generate 5 summarized topics
    prompt_1 = f"""Below is a set of reviews delimited by {TEXT_DELIMITER}:\n{batch}\n
Identify 5 summarized topics (1–4 words) from these reviews.
Return the output as a bullet list, each line one concise topic. No descriptions."""

    text_1 = generate_response(prompt_1)
    print("Raw Topics Output:", text_1)

    extracted_topics = []
    for line in text_1.split("\n"):
        if line.strip():
            match = re.search(r"[-•*]?\s*(.+)", line.strip())
            if match:
                extracted_topics.append(match.group(1).strip())

    print("Extracted Topics:", extracted_topics)

    # Second LLM call: Filter out previously seen topics
    prompt_2 = f"""Given the following topics:\n{extracted_topics}\n
Previously covered topics are: {list(previous_topics)}\n
Return only the new topics not present in the previously covered list.
Output as a bullet list, one topic per line, 1–4 words, no description."""

    text_2 = generate_response(prompt_2)
    print("Filtered Topics Output:", text_2)

    new_topics = []
    for line in text_2.split("\n"):
        if line.strip():
            match = re.search(r"[-•*]?\s*(.+)", line.strip())
            if match:
                topic = match.group(1).strip()
                if topic:
                    new_topics.append(topic)

    print("New Topics:", new_topics)

    # Update broadcasted topics
    if new_topics:
        updated_set = previous_topics.union(set(new_topics))
        previous_topics_broadcast.unpersist()
        previous_topics_broadcast = spark.sparkContext.broadcast(updated_set)

    print("Updated Unique Topics:", previous_topics_broadcast.value)
    print("-" * 50)

    if i == 10: break

print("Final Unique Topics:", previous_topics_broadcast.value)


Processing Batch 1
Raw Topics Output: - Moisturizing
- Lightweight
- Budget-friendly
- Non-greasy
- Suitable for different skin types

These reviews mention various aspects such as effectiveness, ease of use, scent, and suitability for different skin types. Based on the provided information, here are five summarized topics:

- **Moisturizing**: Many reviewers highlight the importance of moisturization in their skincare routines.
- **Lightweight**: Some users appreciate how lightweight the cream feels, especially beneficial for those who prefer lighter
Extracted Topics: ['Moisturizing', 'Lightweight', 'Budget-friendly', 'Non-greasy', 'Suitable for different skin types', 'These reviews mention various aspects such as effectiveness, ease of use, scent, and suitability for different skin types. Based on the provided information, here are five summarized topics:', '**Moisturizing**: Many reviewers highlight the importance of moisturization in their skincare routines.', '**Lightweight**: So

Prompt-chaining, as seen in above code block, reduced hallucinations and improved responses.

Finally, I have called Open AI also below.  
Used prompt-chaining here also.

In [ ]:
#code moved to a different function: generate_responseOpenAI


Processing Batch 1
Raw Topics Output: - Skin Moisturization
- Oily Skin Issues
- Product Effectiveness
- Price Concerns
- Brand Trust
Extracted Topics: ['Skin Moisturization', 'Oily Skin Issues', 'Product Effectiveness', 'Price Concerns', 'Brand Trust']
Filtered Topics Output: - Skin Moisturization
- Oily Skin Issues
- Product Effectiveness
- Price Concerns
- Brand Trust
New Topics: ['Skin Moisturization', 'Oily Skin Issues', 'Product Effectiveness', 'Price Concerns', 'Brand Trust']
Updated Unique Topics: {'Price Concerns', 'Skin Moisturization', 'Brand Trust', 'Product Effectiveness', 'Oily Skin Issues'}
--------------------------------------------------

Processing Batch 2
Raw Topics Output: - Skin Moisturization
- Price Concerns
- Anti-Aging Effects
- Suitable for All Skin Types
- Positive User Experience
Extracted Topics: ['Skin Moisturization', 'Price Concerns', 'Anti-Aging Effects', 'Suitable for All Skin Types', 'Positive User Experience']
Filtered Topics Output: - Anti-Aging E

***Section 4: Routing query and answering query***

In [ ]:
!cp '/content/drive/MyDrive/BAX_493_Homeworks/BAX493_FinalProject/query_router.ipynb' /content/sample_data
%run /content/sample_data/query_router.ipynb

***Run below code to run the query. It will call other components as needed***.  
Running queries one-by-one below

In [ ]:
query_list = ["What is the ingredient list of Bioderma Photoderm LEB Spf 30?"]
for query in query_list:
  print(f"Prompt is: {query}")
  print("Step 1: Routing query...")
  channel = router(query)
  print(f"✓ Routed to: {channel} channel")
  # Step 2: Process through appropriate channel
  print(f"\nProcessing through {channel} channel...")

  if channel == "FACTUAL":
    try:
      factual_answers(query, collection)
      # print(f"Final Response: {factual_answers(query)}")
    except: print("Incorrect routing of query. Cannot answer.")
  elif channel == "WEB_SEARCH":
    try:
      answer = react_agent(query)
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "CUSTOMER_REVIEWS":
    try:
      temp = query.split('about')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_topic_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "SENTIMENT_ANALYSIS":
    try:
      temp = query.split('around')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_sentiment_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  else:
    print("Nothing found")
# Routed and answered correctly

Prompt is: What is the ingredient list of Bioderma Photoderm LEB Spf 30?
Step 1: Routing query...
✓ Routed to: WEB_SEARCH channel

Processing through WEB_SEARCH channel...
text:  I should look up the ingredient list of Bioderma Photoderm LEB Spf 30.
Action: Search("ingredient list of Bioderma Photoderm LEB Spf 30")
Searching for: ingredient list of Bioderma Photoderm LEB Spf 30
https://incidecoder.com/products/bioderma-photoderm-leb-spf-30


[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
448961187&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528500~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1457143767.17
54448961&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&
uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754448961&sct=1&seg=0&dl=https%3A%2F%2Fincidecod
er.com%2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explain
ed)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=753' because it violates the following Content Security Policy directive: 
"connect-src 'self' https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
48961187&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528500~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1457143767.175
4448961&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&u
am=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754448961&sct=1&seg=0&dl=https%3A%2F%2Fincidecode
r.com%2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explaine
d)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=753. Refused to connect because it violates the document's Content Security 
Policy. 

[CONSOLE]. ℹ Console: Failed to load resource: the server responded with a status of 500 () 

[CONSOLE]. ℹ Console error: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
448961187&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528500~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1457143767.17
54448961&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&
uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754448961&sct=1&seg=0&dl=https%3A%2F
%2Fincidecoder.com%2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredient
s%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=2637&tfd=8401' because it violates the following Content 
Security Policy directive: "connect-src 'self' https://incidecoder-content.storage.googleapis.com  
https://www.google-analytics.com https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
48961187&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528500~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1457143767.175
4448961&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&u
am=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754448961&sct=1&seg=0&dl=https%3A%2F%
2Fincidecoder.com%2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients
%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=2637&tfd=8401. Refused to connect because it violates the 
document's Content Security Policy. 

[FETCH]... ↓ https://incidecoder.com/products/bioderma-photoderm-leb-spf-30                                       |
✓ | ⏱: 14.16s 

[SCRAPE].. ◆ https://incidecoder.com/products/bioderma-photoderm-leb-spf-30                                       |
✓ | ⏱: 0.17s 

[COMPLETE] ● https://incidecoder.com/products/bioderma-photoderm-leb-spf-30                                       |
✓ | ⏱: 14.34s 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
448961187&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528500~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1457143767.17
54448961&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&
uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754448961&sct=1&seg=1&dl=https%3A%2F
%2Fincidecoder.com%2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredient
s%20(Explained)&en=user_engagement&_et=10437&tfd=13844' because it violates the following Content Security Policy 
directive: "connect-src 'self' https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
48961187&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528500~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1457143767.175
4448961&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&u
am=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754448961&sct=1&seg=1&dl=https%3A%2F%
2Fincidecoder.com%2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients
%20(Explained)&en=user_engagement&_et=10437&tfd=13844. Refused to connect because it violates the document's 
Content Security Policy. 

There are a total of 29 ingredients, as listed on INCIdecoder: 

1:Aqua/​Water/​Eau 
2:Dicaprylyl Carbonate 
3:Diisopropyl Sebacate 
4:Methylene Bis-Benzotriazolyl Tetramethylbutylphenol 
5:Butyl Methoxydibenzoylmethane 
6:Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine 
7:Cyclopentasiloxane 
8:Methylpropanediol 
9:Decyl Glucoside 
10:more 
11:Ectoin 
12:Xylitol 
13:Rhamnose 
14:Fructooligosaccharides 
15:Laminaria Ochroleuca Extract 
16:C20-22 Alkyl Phosphate 
17:C20-22 Alcohols 
18:Microcrystalline Cellulose 
19:Coco-Glucoside 
20:Xanthan Gum 
21:Cellulose Gum 
22:Pentylene Glycol 
23:Propylene Glycol 
24:Cetearyl Alcohol 
25:Caprylic/​Capric Triglyceride 
26:Sodium Hydroxide 
27:Disodium Edta 
28:Phenoxyethanol 
29:Chlorphenesin 
Search results: There are a total of 29 ingredients, as listed on INCIdecoder: 
1:Aqua/​Water/​Eau
2:Dicaprylyl Carbonate
3:Diisopropyl Sebacate
4:Methylene Bis-Benzotriazolyl Tetramethylbutylphenol
5:Butyl Methoxydibenzoylmethane
6:Bis-Ethylhexyloxyphenol M

In [ ]:
query_list = ["What is the ingredient list of The Ordinary Mineral Uv Filters Spf 30 With Antioxidants?"]
for query in query_list:
  print(f"Prompt is: {query}")
  print("Step 1: Routing query...")
  channel = router(query)
  print(f"✓ Routed to: {channel} channel")
  # Step 2: Process through appropriate channel
  print(f"\nProcessing through {channel} channel...")

  if channel == "FACTUAL":
    try:
      factual_answers(query, collection)
      # print(f"Final Response: {factual_answers(query)}")
    except: print("Incorrect routing of query. Cannot answer.")
  elif channel == "WEB_SEARCH":
    try:
      answer = react_agent(query)
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "CUSTOMER_REVIEWS":
    try:
      temp = query.split('about')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_topic_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "SENTIMENT_ANALYSIS":
    try:
      temp = query.split('around')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_sentiment_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  else:
    print("Nothing found")
# Routed and answered correctly

Prompt is: What is the ingredient list of The Ordinary Mineral Uv Filters Spf 30 With Antioxidants?
Step 1: Routing query...
✓ Routed to: WEB_SEARCH channel

Processing through WEB_SEARCH channel...
text:  I should look up the ingredient list of The Ordinary Mineral Uv Filters Spf 30 With Antioxidants.
Action: Search("ingredient list of The Ordinary Mineral Uv Filters Spf 30 With Antioxidants")
Searching for: ingredient list of The Ordinary Mineral Uv Filters Spf 30 With Antioxidants
https://incidecoder.com/products/the-ordinary-mineral-uv-filters-spf-30-with-antioxidants


[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
449036177&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=974874165.1754449036&ul=en-us&sr=
1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Windows&uapv
=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754449036&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fproducts%2Ft
he-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Spf%2030%20Wit
h%20Antioxidants%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=819' because it violates the 
following Content Security Policy directive: "connect-src 'self' https://incidecoder-content.storage.googleapis.com
https://www.google-analytics.com https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
49036177&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=974874165.1754449036&ul=en-us&sr=1
280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Windows&uapv=
10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754449036&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fproducts%2Fth
e-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Spf%2030%20With
%20Antioxidants%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=819. Refused to connect because it 
violates the document's Content Security Policy. 

[CONSOLE]. ℹ Console: Failed to load resource: the server responded with a status of 500 () 

[CONSOLE]. ℹ Console error: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
449036177&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=974874165.1754449036&ul=en-us&sr=
1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Windows&uapv
=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754449036&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2F
products%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Sp
f%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=3742&tfd=9566' 
because it violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
49036177&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=974874165.1754449036&ul=en-us&sr=1
280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Windows&uapv=
10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754449036&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fp
roducts%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Spf
%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=3742&tfd=9566. 
Refused to connect because it violates the document's Content Security Policy. 

[FETCH]... ↓ https://incidecoder.com/products/the-ordinary-mineral-uv-filters-spf-30-with-antioxidants            |
✓ | ⏱: 14.26s 

[SCRAPE].. ◆ https://incidecoder.com/products/the-ordinary-mineral-uv-filters-spf-30-with-antioxidants            |
✓ | ⏱: 0.35s 

[COMPLETE] ● https://incidecoder.com/products/the-ordinary-mineral-uv-filters-spf-30-with-antioxidants            |
✓ | ⏱: 14.61s 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
449036177&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=974874165.1754449036&ul=en-us&sr=
1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Windows&uapv
=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754449036&sct=1&seg=1&dl=https%3A%2F%2Fincidecoder.com%2F
products%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Sp
f%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=user_engagement&_et=9522&tfd=14092' because it violates
the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
49036177&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=974874165.1754449036&ul=en-us&sr=1
280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Windows&uapv=
10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754449036&sct=1&seg=1&dl=https%3A%2F%2Fincidecoder.com%2Fp
roducts%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Spf
%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=user_engagement&_et=9522&tfd=14092. Refused to connect 
because it violates the document's Content Security Policy. 

There are a total of 63 ingredients, as listed on INCIdecoder: 

1:Aqua (Water) 
2:Cyclopentasiloxane 
3:Zinc Oxide 
4:Titanium Dioxide 
5:Peg-10 Dimethicone 
6:Glycerin 
7:Helianthus Annuus Seed Oil 
8:Peg-9 Polydimethylsiloxyethyl Dimethicone 
9:Hexyl Laurate 
10:more 
11:Polyglyceryl-4 Isostearate 
12:Caprylic/​Capric Triglyceride 
13:Dimethicone/​Peg-10/​15 Crosspolymer 
14:Astaxanthin 
15:Disodium Uridine Phosphate 
16:Ethyl Ferulate 
17:Rosmarinus Officinalis Leaf Extract 
18:Tasmannia Lanceolata Fruit/​Leaf Extract 
19:Haematococcus Pluvialis Extract 
20:Picea Mariana Bark Extract 
21:Arginine 
22:Aspartic Acid 
23:Glycine 
24:Alanine 
25:Serine 
26:Valine 
27:Isoleucine 
28:Proline 
29:Threonine 
30:Histidine 
31:Phenylalanine 
32:Sodium Pca 
33:Pca 
34:Sodium Lactate 
35:Glucose 
36:Maltose 
37:Fructose 
38:Trehalose 
39:Urea 
40:Allantoin 
41:Sodium Hyaluronate 
42:Linoleic Acid 
43:Oleic Acid 
44:Phytosteryl Canola Glycerides 
45:Palmitic Acid 
46:Stearic Acid 
47:Isochrysis

In [ ]:
query_list = ["What are customers saying about Olay Eye Cream - With Niacinamide & Pentapeptides on the Internet?"]
for query in query_list:
  print(f"Prompt is: {query}")
  print("Step 1: Routing query...")
  channel = router(query)
  print(f"✓ Routed to: {channel} channel")
  # Step 2: Process through appropriate channel
  print(f"\nProcessing through {channel} channel...")

  if channel == "FACTUAL":
    try:
      factual_answers(query, collection)
      # print(f"Final Response: {factual_answers(query)}")
    except: print("Incorrect routing of query. Cannot answer.")
  elif channel == "WEB_SEARCH":
    try:
      answer = react_agent(query)
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "CUSTOMER_REVIEWS":
    try:
      temp = query.split('about')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_topic_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "SENTIMENT_ANALYSIS":
    try:
      temp = query.split('around')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_sentiment_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  else:
    print("Nothing found")

# Routed and answered correctly

Prompt is: What are customers saying about Olay Eye Cream - With Niacinamide & Pentapeptides on the Internet?
Step 1: Routing query...
✓ Routed to: CUSTOMER_REVIEWS channel

Processing through CUSTOMER_REVIEWS channel...
Partition 1:

####NOT EFFECTIVE. This product is not effective at all...its a waste of money.####Good product. It applies well and feels good on the skin. It contains texture enhancing super emollients. This cream is just right. Effective without being greasy, as always, and definitely helps with smoothing out the lines and wrinkles.####Very bad eye cream. My under eyes are dark and dry after using this cream..waste of money….####No change.... Wrost product.. cost is high.. waste of money####Disgusting. Too sticky & bad smell. DO NOT BUY!####Worst product I ever had in my life. Guys please don't buy this product..i will share what experience i had after using this 2 month it just drys my eye area i never had dryness problem because have combination skin and credit goes

In [ ]:
torch.cuda.empty_cache()
query_list = ["What is the customer sentiment around Nykaa Metal Addict Makeup Bag - Blushing Gold on the Internet?"]
for query in query_list:
  print(f"Prompt is: {query}")
  print("Step 1: Routing query...")
  channel = router(query)
  print(f"✓ Routed to: {channel} channel")
  # Step 2: Process through appropriate channel
  print(f"\nProcessing through {channel} channel...")

  if channel == "FACTUAL":
    try:
      factual_answers(query, collection)
      # print(f"Final Response: {factual_answers(query)}")
    except: print("Incorrect routing of query. Cannot answer.")
  elif channel == "WEB_SEARCH":
    try:
      answer = react_agent(query)
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "CUSTOMER_REVIEWS":
    try:
      temp = query.split('about')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_topic_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "SENTIMENT_ANALYSIS":
    try:
      temp = query.split('around')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_sentiment_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  else:
    print("Nothing found")

# Routed and answered correctly

Prompt is: What is the customer sentiment around Nykaa Metal Addict Makeup Bag - Blushing Gold on the Internet?
Step 1: Routing query...
✓ Routed to: SENTIMENT_ANALYSIS channel

Processing through SENTIMENT_ANALYSIS channel...
Partition 1:

####Cute. These bags are so cute. This is my second one. Been using the other one for about an year now. These are very durable.####Bah. Wow nice bag it carry many makeup product that I use I love it####Superb. I loved this pouch all my mini products fit in nicely...####Shiney n specious. Very specious can carry basic makeup products in it.####Bag. Omgggg!!!! This is sooooo prettyyyyy... So shiny . Loved it####Lady of steel. Material's really good and very handy to carry and it's very spacious, able to hold a lot of products in it.####It's cute. I love this bag it large in space. It does look small but it's not####Loved it.. Loved it. Good quality and more spacious than seems.####Very very nice..... Nice colour & nice quality.....cute...####Its nice

In [ ]:
torch.cuda.empty_cache()
query_list = ["Is zirconium-containing complexes in cosmetics safe?"]
for query in query_list:
  print(f"Prompt is: {query}")
  print("Step 1: Routing query...")
  channel = router(query)
  print(f"✓ Routed to: {channel} channel")
  # Step 2: Process through appropriate channel
  print(f"\nProcessing through {channel} channel...")

  if channel == "FACTUAL":
    try:
      factual_answers(query, collection)
      # print(f"Final Response: {factual_answers(query)}")
    except: print("Incorrect routing of query. Cannot answer.")
  elif channel == "WEB_SEARCH":
    try:
      answer = react_agent(query)
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "CUSTOMER_REVIEWS":
    try:
      temp = query.split('about')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_topic_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "SENTIMENT_ANALYSIS":
    try:
      temp = query.split('around')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_sentiment_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  else:
    print("Nothing found")

# Routed and answered correctly

Prompt is: Is zirconium-containing complexes in cosmetics safe?
Step 1: Routing query...
✓ Routed to: FACTUAL channel

Processing through FACTUAL channel...
{'ids': [['188', '438', '1235', '1029', '432']], 'embeddings': None, 'documents': [['Abstract: The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 27 inorganic and organometallic zinc salts as used in cosmetic formulations; these salts are specifically of the  ', 'Abstract: The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 47  ', 'Abstract: The Cosmetic Ingredient Review Expert Panel assessed the safety of bis-diglyceryl polyacyladipate-2 and bis-diglyceryl polyacyladipate-1 as used in cosmetics, finding that these ingredients are safe in cosmetic formulations in the present practices of use and concentration. Both ingredients are lanolin substitutes and are reported to function in cosmetics as skin-conditioning agents--emollients. The Panel reviewed available animal and clini

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


The Expert Panel for Cosmetic Ingredient Safety (Panel) assessed the safety of 30 zirconium-containing complexes as used in cosmetic formulations; these complexes are specifically of the following types:

1. Zirconium(IV) oxide hydrate
2. Zirconium(IV) carbonate
3. Zirconium(IV) hydroxide
4. Zirconium(IV) sulfate
5. Zirconium(IV) nitrate
6. Zirconium(IV) chloride
7. Zirconium(IV) bromide
8. Zirconium(IV) iodide
9. Zircon


-----




In [ ]:
query_list = ["What is the ingredient list of Bioderma Photoderm LEB Spf 30?",
              "What is the ingredient list of The Ordinary Mineral Uv Filters Spf 30 With Antioxidants?",
              "What is the ingredient list of Bioderma Hydrabio Creme?",
              "What are customers saying about Nykaa Skin Secrets Tea Tree & Salicylic Acid Spot Patch on the Internet?",
              "What is the customer sentiment around Olay Aha & Niacinamide Super Cream , Acne Mark & Spot Removal Cream - For All Skin Types on the Internet?",
              "What are customers saying about Nykaa Metal Addict Makeup Bag - Blushing Gold on the Internet?",
              "What is the customer sentiment around Nykaa Metal Addict Makeup Bag - Blushing Gold on the Internet?",
              "Can formaldehyde in nail hardeners or hair‑smoothing keratin treatments increase cancer risk?",
              "Is zirconium-containing complexes in cosmetics safe?",
              "Could mercury in skin‑lightening creams or mascara pose risks for kidney damage?"]
for query in query_list:
  print(f"Prompt is: {query}")
  print("Step 1: Routing query...")
  channel = router(query)
  print(f"✓ Routed to: {channel} channel")
  # Step 2: Process through appropriate channel
  print(f"\nProcessing through {channel} channel...")

  if channel == "FACTUAL":
    try:
      factual_answers(query, collection)
      # print(f"Final Response: {factual_answers(query)}")
    except: print("Incorrect routing of query. Cannot answer.")
  elif channel == "WEB_SEARCH":
    try:
      answer = react_agent(query)
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "CUSTOMER_REVIEWS":
    try:
      temp = query.split('about')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_topic_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  elif channel == "SENTIMENT_ANALYSIS":
    try:
      temp = query.split('around')[1]
      product_name = temp.split('on')[0]
      answer = customer_review_sentiment_modeling(product_name.strip())
      print(f"\nFinal Agent Answer: {answer}")
    except:
      print("Incorrect routing of query. Cannot answer.")
  else:
    print("Nothing found")
  torch.cuda.empty_cache()

# Routed and answered most queries correctly
# Incorrectly routed 3 queries.
# I noticed a weird thing happening. When a list of test_prompts are given, the LLM carries context from the previous prompt while answering the next prompt.
# Example, while answering the next question, unrelated to the previous one, it started rejurgitating facts like-
# I should look up information about the ingredient list of Olay skin-lightening cream. This was related to the previous query.
# On further research, I realized that this is a common problem. It is called context carryover
# Source: https://arxiv.org/html/2410.12586v2
# I tried torch.cuda.empty_cache() as a small fix. But this continued to happen.

Prompt is: What is the ingredient list of Bioderma Photoderm LEB Spf 30?
Step 1: Routing query...
✓ Routed to: WEB_SEARCH channel

Processing through WEB_SEARCH channel...
text:  I should look up the ingredient list of Bioderma Photoderm LEB Spf 30.
Action: Search("ingredient list of Bioderma Photoderm LEB Spf 30")
Searching for: ingredient list of Bioderma Photoderm LEB Spf 30
https://incidecoder.com/products/bioderma-photoderm-leb-spf-30


[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452605457&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1291855345.1754452606&ul=en-us&sr
=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=macOS&uapv=
10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452605&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fproducts%2
Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explained)&en=page_view&_f
v=1&_ss=1&_ee=1&tfd=685' because it violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52605457&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1291855345.1754452606&ul=en-us&sr=
1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=macOS&uapv=1
0_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452605&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fproducts%2F
bioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explained)&en=page_view&_fv
=1&_ss=1&_ee=1&tfd=685. Refused to connect because it violates the document's Content Security Policy. 

[CONSOLE]. ℹ Console: Failed to load resource: the server responded with a status of 500 () 

[CONSOLE]. ℹ Console error: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452605457&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1291855345.1754452606&ul=en-us&sr
=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=macOS&uapv=
10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452605&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%
2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explained)&en=
scroll&epn.percent_scrolled=90&_et=2525&tfd=8214' because it violates the following Content Security Policy 
directive: "connect-src 'self' https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52605457&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1291855345.1754452606&ul=en-us&sr=
1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=macOS&uapv=1
0_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452605&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2
Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explained)&en=s
croll&epn.percent_scrolled=90&_et=2525&tfd=8214. Refused to connect because it violates the document's Content 
Security Policy. 

[FETCH]... ↓ https://incidecoder.com/products/bioderma-photoderm-leb-spf-30                                       |
✓ | ⏱: 13.18s 

[SCRAPE].. ◆ https://incidecoder.com/products/bioderma-photoderm-leb-spf-30                                       |
✓ | ⏱: 0.17s 

[COMPLETE] ● https://incidecoder.com/products/bioderma-photoderm-leb-spf-30                                       |
✓ | ⏱: 13.36s 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452605457&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1291855345.1754452606&ul=en-us&sr
=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=macOS&uapv=
10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452605&sct=1&seg=1&dl=https%3A%2F%2Fincidecoder.com%
2Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explained)&en=
user_engagement&_et=9711&tfd=12933' because it violates the following Content Security Policy directive: 
"connect-src 'self' https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52605457&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1291855345.1754452606&ul=en-us&sr=
1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=macOS&uapv=1
0_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452605&sct=1&seg=1&dl=https%3A%2F%2Fincidecoder.com%2
Fproducts%2Fbioderma-photoderm-leb-spf-30&dt=Bioderma%20Photoderm%20LEB%20Spf%2030%20ingredients%20(Explained)&en=u
ser_engagement&_et=9711&tfd=12933. Refused to connect because it violates the document's Content Security Policy. 

There are a total of 29 ingredients, as listed on INCIdecoder: 

1:Aqua/​Water/​Eau 
2:Dicaprylyl Carbonate 
3:Diisopropyl Sebacate 
4:Methylene Bis-Benzotriazolyl Tetramethylbutylphenol 
5:Butyl Methoxydibenzoylmethane 
6:Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine 
7:Cyclopentasiloxane 
8:Methylpropanediol 
9:Decyl Glucoside 
10:more 
11:Ectoin 
12:Xylitol 
13:Rhamnose 
14:Fructooligosaccharides 
15:Laminaria Ochroleuca Extract 
16:C20-22 Alkyl Phosphate 
17:C20-22 Alcohols 
18:Microcrystalline Cellulose 
19:Coco-Glucoside 
20:Xanthan Gum 
21:Cellulose Gum 
22:Pentylene Glycol 
23:Propylene Glycol 
24:Cetearyl Alcohol 
25:Caprylic/​Capric Triglyceride 
26:Sodium Hydroxide 
27:Disodium Edta 
28:Phenoxyethanol 
29:Chlorphenesin 
Search results: There are a total of 29 ingredients, as listed on INCIdecoder: 
1:Aqua/​Water/​Eau
2:Dicaprylyl Carbonate
3:Diisopropyl Sebacate
4:Methylene Bis-Benzotriazolyl Tetramethylbutylphenol
5:Butyl Methoxydibenzoylmethane
6:Bis-Ethylhexyloxyphenol M

[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452636802&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105113531&cid=2114102191.1754452637&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=m
acOS&uapv=10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452637&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2F
products%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Sp
f%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=1212' because it 
violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52636802&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105113531&cid=2114102191.1754452637&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=ma
cOS&uapv=10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452637&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fp
roducts%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20Filters%20Spf
%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=1212. Refused to connect
because it violates the document's Content Security Policy. 

[CONSOLE]. ℹ Console: Failed to load resource: the server responded with a status of 500 () 

[CONSOLE]. ℹ Console error: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452636802&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105113531&cid=2114102191.1754452637&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=m
acOS&uapv=10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452637&sct=1&seg=0&dl=https%3A%2F%2Fincide
coder.com%2Fproducts%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20
Filters%20Spf%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=3705&tfd
=9922' because it violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52636802&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105113531&cid=2114102191.1754452637&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=ma
cOS&uapv=10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452637&sct=1&seg=0&dl=https%3A%2F%2Fincidec
oder.com%2Fproducts%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20F
ilters%20Spf%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=3705&tfd=
9922. Refused to connect because it violates the document's Content Security Policy. 

[FETCH]... ↓ https://incidecoder.com/products/the-ordinary-mineral-uv-filters-spf-30-with-antioxidants            |
✓ | ⏱: 14.05s 

[SCRAPE].. ◆ https://incidecoder.com/products/the-ordinary-mineral-uv-filters-spf-30-with-antioxidants            |
✓ | ⏱: 0.34s 

[COMPLETE] ● https://incidecoder.com/products/the-ordinary-mineral-uv-filters-spf-30-with-antioxidants            |
✓ | ⏱: 14.40s 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452636802&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~10
4528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105113531&cid=2114102191.1754452637&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=m
acOS&uapv=10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452637&sct=1&seg=1&dl=https%3A%2F%2Fincide
coder.com%2Fproducts%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20
Filters%20Spf%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=user_engagement&_et=8981&tfd=13909' because
it violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52636802&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527906~104
528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105113531&cid=2114102191.1754452637&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=ma
cOS&uapv=10_15_7&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452637&sct=1&seg=1&dl=https%3A%2F%2Fincidec
oder.com%2Fproducts%2Fthe-ordinary-mineral-uv-filters-spf-30-with-antioxidants&dt=The%20Ordinary%20Mineral%20Uv%20F
ilters%20Spf%2030%20With%20Antioxidants%20ingredients%20(Explained)&en=user_engagement&_et=8981&tfd=13909. Refused 
to connect because it violates the document's Content Security Policy. 

There are a total of 63 ingredients, as listed on INCIdecoder: 

1:Aqua (Water) 
2:Cyclopentasiloxane 
3:Zinc Oxide 
4:Titanium Dioxide 
5:Peg-10 Dimethicone 
6:Glycerin 
7:Helianthus Annuus Seed Oil 
8:Peg-9 Polydimethylsiloxyethyl Dimethicone 
9:Hexyl Laurate 
10:more 
11:Polyglyceryl-4 Isostearate 
12:Caprylic/​Capric Triglyceride 
13:Dimethicone/​Peg-10/​15 Crosspolymer 
14:Astaxanthin 
15:Disodium Uridine Phosphate 
16:Ethyl Ferulate 
17:Rosmarinus Officinalis Leaf Extract 
18:Tasmannia Lanceolata Fruit/​Leaf Extract 
19:Haematococcus Pluvialis Extract 
20:Picea Mariana Bark Extract 
21:Arginine 
22:Aspartic Acid 
23:Glycine 
24:Alanine 
25:Serine 
26:Valine 
27:Isoleucine 
28:Proline 
29:Threonine 
30:Histidine 
31:Phenylalanine 
32:Sodium Pca 
33:Pca 
34:Sodium Lactate 
35:Glucose 
36:Maltose 
37:Fructose 
38:Trehalose 
39:Urea 
40:Allantoin 
41:Sodium Hyaluronate 
42:Linoleic Acid 
43:Oleic Acid 
44:Phytosteryl Canola Glycerides 
45:Palmitic Acid 
46:Stearic Acid 
47:Isochrysis

[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452671102&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528500~104573694~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1084676463.1754452671&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=W
indows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452671&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fp
roducts%2Fbioderma-hydrabio-creme&dt=Bioderma%20Hydrabio%20Creme%20ingredients%20(Explained)&en=page_view&_fv=1&_ss
=1&_ee=1&tfd=1346' because it violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52671102&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528500~104573694~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1084676463.1754452671&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Wi
ndows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452671&sct=1&seg=0&dl=https%3A%2F%2Fincidecoder.com%2Fpr
oducts%2Fbioderma-hydrabio-creme&dt=Bioderma%20Hydrabio%20Creme%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=
1&_ee=1&tfd=1346. Refused to connect because it violates the document's Content Security Policy. 

[CONSOLE]. ℹ Console: Failed to load resource: the server responded with a status of 500 () 

[CONSOLE]. ℹ Console error: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452671102&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528500~104573694~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1084676463.1754452671&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=W
indows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452671&sct=1&seg=0&dl=https%3A%2F%2Fincidec
oder.com%2Fproducts%2Fbioderma-hydrabio-creme&dt=Bioderma%20Hydrabio%20Creme%20ingredients%20(Explained)&en=scroll&
epn.percent_scrolled=90&_et=3956&tfd=10310' because it violates the following Content Security Policy directive: 
"connect-src 'self' https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52671102&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528500~104573694~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1084676463.1754452671&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Wi
ndows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452671&sct=1&seg=0&dl=https%3A%2F%2Fincideco
der.com%2Fproducts%2Fbioderma-hydrabio-creme&dt=Bioderma%20Hydrabio%20Creme%20ingredients%20(Explained)&en=scroll&e
pn.percent_scrolled=90&_et=3956&tfd=10310. Refused to connect because it violates the document's Content Security 
Policy. 

[FETCH]... ↓ https://incidecoder.com/products/bioderma-hydrabio-creme                                             |
✓ | ⏱: 14.56s 

[SCRAPE].. ◆ https://incidecoder.com/products/bioderma-hydrabio-creme                                             |
✓ | ⏱: 0.15s 

[COMPLETE] ● https://incidecoder.com/products/bioderma-hydrabio-creme                                             |
✓ | ⏱: 14.71s 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452671102&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~10
4528500~104573694~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1084676463.1754452671&u
l=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=W
indows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452671&sct=1&seg=1&dl=https%3A%2F%2Fincidec
oder.com%2Fproducts%2Fbioderma-hydrabio-creme&dt=Bioderma%20Hydrabio%20Creme%20ingredients%20(Explained)&en=user_en
gagement&_et=8872&tfd=14186' because it violates the following Content Security Policy directive: "connect-src 
'self' https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52671102&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~103116026~103200004~103233427~104527907~104
528500~104573694~104684208~104684211~104948813~105087538~105087540~105103161~105103163&cid=1084676463.1754452671&ul
=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.0&uamb=0&uam=&uap=Wi
ndows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452671&sct=1&seg=1&dl=https%3A%2F%2Fincideco
der.com%2Fproducts%2Fbioderma-hydrabio-creme&dt=Bioderma%20Hydrabio%20Creme%20ingredients%20(Explained)&en=user_eng
agement&_et=8872&tfd=14186. Refused to connect because it violates the document's Content Security Policy. 

There are a total of 40 ingredients, as listed on INCIdecoder: 

1:Aqua/​Water/​Eau 
2:Glycerin 
3:Isododecane 
4:Cyclopentasiloxane 
5:Propylene Glycol Dicaprylate/​Dicaprate 
6:Dimethicone 
7:Propanediol 
8:Xylitol 
9:Cetyl Palmitate 
10:more 
11:Hydrogenated Polydecene 
12:Niacinamide 
13:Tridecyl Trimellitate 
14:Arachidyl Alcohol 
15:Polymethylsilsesquioxane 
16:Glyceryl Dibehenate 
17:Behenyl Alcohol 
18:Hdi/​Trimethylol Hexyllactone Crosspolymer 
19:Tribehenin 
20:Dimethicone/​Vinyl Dimethicone Crosspolymer 
21:Pentylene Glycol 
22:Tocopheryl Acetate 
23:Arachidyl Glucoside 
24:Acrylates/​C10-30 Alkyl Acrylate Crosspolymer 
25:Hydroxyethyl Acrylate/​Sodium Acryloyldimethyl Taurate Copolymer 
26:Glyceryl Behenate 
27:Disodium Edta 
28:Squalane 
29:Salicylic Acid 
30:Sodium Hydroxide 
31:Mannitol 
32:Sodium Hyaluronate 
33:Hexyldecanol 
34:Tocopherol 
35:Polysorbate 60 
36:Rhamnose 
37:Helianthus Annuus (Sunflower) Seed Oil 
38:Pyrus Malus (Apple) Seed Extract 
39:Brassica Campest

[INIT].... → Crawl4AI 0.7.2 

[CONSOLE]. ℹ Console error: Cannot redefine property: webdriver 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452732508&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~102015666~103116026~103200004~103233427~10
4527907~104528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=118
1132117.1754452733&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0
.0&uamb=0&uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452733&sct=1&seg=0&dl=https%3A%2F%2
Fincidecoder.com%2Fproducts%2Folay-super-cream-with-sunscreen-spf-30&dt=Olay%20Super%20Cream%20With%20Sunscreen%20S
PF%2030%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=1241' because it violates the following 
Content Security Policy directive: "connect-src 'self' https://incidecoder-content.storage.googleapis.com  
https://www.google-analytics.com https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52732508&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~102015666~103116026~103200004~103233427~104
527907~104528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1181
132117.1754452733&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.
0&uamb=0&uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1754452733&sct=1&seg=0&dl=https%3A%2F%2F
incidecoder.com%2Fproducts%2Folay-super-cream-with-sunscreen-spf-30&dt=Olay%20Super%20Cream%20With%20Sunscreen%20SP
F%2030%20ingredients%20(Explained)&en=page_view&_fv=1&_ss=1&_ee=1&tfd=1241. Refused to connect because it violates 
the document's Content Security Policy. 

[CONSOLE]. ℹ Console: Failed to load resource: the server responded with a status of 500 () 

[CONSOLE]. ℹ Console error: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452732508&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~102015666~103116026~103200004~103233427~10
4527907~104528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=118
1132117.1754452733&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0
.0&uamb=0&uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452733&sct=1&seg=0&dl=h
ttps%3A%2F%2Fincidecoder.com%2Fproducts%2Folay-super-cream-with-sunscreen-spf-30&dt=Olay%20Super%20Cream%20With%20S
unscreen%20SPF%2030%20ingredients%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=3790&tfd=10034' because it 
violates the following Content Security Policy directive: "connect-src 'self' 
https://incidecoder-content.storage.googleapis.com  https://www.google-analytics.com 
https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52732508&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~102015666~103116026~103200004~103233427~104
527907~104528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1181
132117.1754452733&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.
0&uamb=0&uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AEAAAAQ&_s=2&sid=1754452733&sct=1&seg=0&dl=ht
tps%3A%2F%2Fincidecoder.com%2Fproducts%2Folay-super-cream-with-sunscreen-spf-30&dt=Olay%20Super%20Cream%20With%20Su
nscreen%20SPF%2030%20ingredients%20(Explained)&en=scroll&epn.percent_scrolled=90&_et=3790&tfd=10034. Refused to 
connect because it violates the document's Content Security Policy. 

[FETCH]... ↓ https://incidecoder.com/products/olay-super-cream-with-sunscreen-spf-30                              |
✓ | ⏱: 14.16s 

[SCRAPE].. ◆ https://incidecoder.com/products/olay-super-cream-with-sunscreen-spf-30                              |
✓ | ⏱: 0.23s 

[COMPLETE] ● https://incidecoder.com/products/olay-super-cream-with-sunscreen-spf-30                              |
✓ | ⏱: 14.40s 

[CONSOLE]. ℹ Console: Refused to connect to 
'https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=1754
452732508&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~102015666~103116026~103200004~103233427~10
4527907~104528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=118
1132117.1754452733&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0
.0&uamb=0&uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452733&sct=1&seg=1&dl=h
ttps%3A%2F%2Fincidecoder.com%2Fproducts%2Folay-super-cream-with-sunscreen-spf-30&dt=Olay%20Super%20Cream%20With%20S
unscreen%20SPF%2030%20ingredients%20(Explained)&en=user_engagement&_et=8580&tfd=13621' because it violates the 
following Content Security Policy directive: "connect-src 'self' https://incidecoder-content.storage.googleapis.com
https://www.google-analytics.com https://www.googletagmanager.com https://www.facebook.com".
 

[CONSOLE]. ℹ Console: Fetch API cannot load 
https://region1.google-analytics.com/g/collect?v=2&tid=G-WSCGSQYT7T&gtm=45je5841v895230066za200zd895230066&_p=17544
52732508&gcd=13l3l3l2l1l1&npa=1&dma_cps=syphamo&dma=1&tag_exp=101509157~102015666~103116026~103200004~103233427~104
527907~104528501~104684208~104684211~104948813~105087538~105087540~105103161~105103163~105135708~105135710&cid=1181
132117.1754452733&ul=en-us&sr=1280x800&uaa=x86&uab=64&uafvl=Chromium%3B139.0.7258.5%7CNot%253BA%253DBrand%3B99.0.0.
0&uamb=0&uam=&uap=Windows&uapv=10.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=AAAAAAQ&_s=3&sid=1754452733&sct=1&seg=1&dl=ht
tps%3A%2F%2Fincidecoder.com%2Fproducts%2Folay-super-cream-with-sunscreen-spf-30&dt=Olay%20Super%20Cream%20With%20Su
nscreen%20SPF%2030%20ingredients%20(Explained)&en=user_engagement&_et=8580&tfd=13621. Refused to connect because it
violates the document's Content Security Policy. 

There are a total of 30 ingredients, as listed on INCIdecoder: 

1:Water 
2:Zea Mays (Corn) Starch 
3:Glycerin 
4:Niacinamide* 
5:Dimethicone 
6:3-O-Ethyl Ascorbic Acid** 
7:Sodium Hyaluronate*** 
8:Tocopheryl Acetate^ 
9:Palmitoyl Pentapeptide-4*^ 
10:more 
11:Panthenol**^ 
12:Caprylyl Glycol 
13:Dimethiconol 
14:Cetearyl Alcohol 
15:Cetearyl Glucoside 
16:Palmitic Acid 
17:Stearic Acid 
18:Behenyl Alcohol 
19:Stearyl Alcohol 
20:Cetyl Alcohol 
21:Disodium EDTA 
22:PEG-100 Stearate 
23:1,2-Hexanediol 
24:Sodium Polyacrylate Starch 
25:Phenoxyethanol 
26:Fragrance 
27:Avobenzone (3.0%) 
28:Homosalate (9.0%) 
29:Octisalate (4.5%) 
30:Octocrylene (6.0%) 
Search results: There are a total of 30 ingredients, as listed on INCIdecoder: 
1:Water
2:Zea Mays (Corn) Starch
3:Glycerin
4:Niacinamide*
5:Dimethicone
6:3-O-Ethyl Ascorbic Acid**
7:Sodium Hyaluronate***
8:Tocopheryl Acetate^
9:Palmitoyl Pentapeptide-4*^
10:more
11:Panthenol**^
12:Caprylyl Glycol
13:Dimethiconol
14:Cetearyl Alcohol
15:C

In [ ]:
# Uploading model to HuggingFace
!pip install -U transformers datasets huggingface_hub
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from huggingface_hub import login
from peft import PeftModel

# Here, login - opening braces - token - == - "XXX" - closing braces was written. Rewritten like this as github was not allowing push,
# citing privacy issues


merged_model = model.merge_and_unload()

merged_model.push_to_hub("beauty-chatbot")
tokenizer.push_to_hub("beauty-chatbot")

/usr/local/lib/python3.11/dist-packages/peft/tuners/lora/bnb.py:348: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(


Saved model to https://huggingface.co/beauty-chatbot


No files have been modified since last commit. Skipping to prevent empty commit.
No files have been modified since last commit. Skipping to prevent empty commit.


Saved model to https://huggingface.co/beauty-chatbot


In [ ]:
login(token="abc")
merged_model.push_to_hub("beauty-chatbot", commit_message="Force reupload", commit=True)
tokenizer.push_to_hub("beauty-chatbot", commit_message="Force reupload", commit=True)

No files have been modified since last commit. Skipping to prevent empty commit.


Saved model to https://huggingface.co/beauty-chatbot


No files have been modified since last commit. Skipping to prevent empty commit.
